// GENERATED FILE - do not edit by hand.
// Source: data/faults/*.json. Regenerate with: node scripts/build-faultdb.mjs
// hex DTC (first token of F_ORT_TEXT, e.g. "27DA") -> English. used by faults.js.
// not in index.html's script list: injected lazily via loadFaultDb() in faults.js
// so this literal isn't parsed before first paint.
window.BMW_FAULT_DB = {
  // 01xx
  '0100': "Air Flow Sensor HFM",
  '0105': "Atmospheric Pressure Sensor",
  '0110': "Intake Air Temperature Sensor",
  '0115': "Coolant Temperature Sensor",
  '0120': "Pedal Position Sensor 1",
  '0190': "Rail Pressure Sensor",
  // 02xx
  '0200': "Injector Cylinder 1",
  '0201': "Injector Cylinder 5",
  '0202': "Central locking: fuse",
  '0203': "Injector Cylinder 6",
  '0204': "Injector Cylinder 2",
  '0205': "Injector Cylinder 4",
  '0220': "Pedal Position Sensor 2",
  '0235': "Boost Pressure Sensor",
  // 03xx
  '0335': "Crankshaft RPM",
  '03E6': "EGR Regulation",
  // 04xx
  '0400': "EGR",
  '0404': "EGR 2",
  '0480': "Electric ECU Fan",
  // 05xx
  '0500': "Vehicle Speed Sensor Signal",
  '0560': "Internal Reference Voltage",
  // 06xx
  '0600': "DDE Error CAN Controller",
  '0605': "DDE Error",
  // 08xx
  '0801': "Window lift: fuse",
  // 11xx
  '1190': "Rail Pressure Regulation",
  '1195': "Rail Pressure Sensor",
  // 12xx
  '1250': "Delivery Pump Relay",
  '1255': "Delivery Pump Pressure Sensor",
  '1260': "Delivery Pump Control System",
  // 14xx
  '1430': "Boost Pressure or Actuator",
  '1470': "Boost Pressure Regulation",
  // 16xx
  '1612': "DME Incorrectly Coded",
  '1613': "MAP Control",
  '1640': "DDE Error EEPROM or Coding",
  // 1Axx
  '1A04': "Aux. Heater",
  // 1Dxx
  '1DF0': "Engine Stall",
  '1DF5': "EWS - Timeout",
  // 1Exx
  '1E00': "CAN Communication to ASC",
  '1E05': "Vehicle Speed Sensor",
  '1E25': "RPM Regulation",
  '1E30': "Boost Pressure Regulation or Actuator",
  '1E31': "Boost Pressure Regulation",
  '1E35': "Error During Switch off",
  '1E40': "A/D Converter",
  '1E45': "Capacitor Voltage 1 for Cyl 1, 2, 3",
  '1E50': "Capacitor Voltage 2 for Cyl 4, 5, 6",
  '1E55': "RPM Control",
  '1E60': "Power supply Pedal Sensor 1",
  // 27xx
  '2712': "DMTL solenoid valve activation",
  '2713': "Pre-cat lambda sensors swapped",
  '2714': "O2 sensor heater, post-cat, bank 2",
  '2715': "O2 sensor heater, pre-cat, bank 2",
  '2716': "O2 sensor heater, post-cat, bank 1",
  '2717': "Lambda Sensor Heater Post Cat Bank 2",
  '2718': "Crankshaft sensor reference",
  '2719': "Crankshaft sensor period",
  '271A': "O2 sensor pre-cat, bank 1 (signal)",
  '271C': "O2 sensor post-cat, bank 1 (signal)",
  '271D': "O2 sensor heater, pre-cat, bank 1",
  '271E': "O2 sensor heater, post-cat, bank 1",
  '271F': "Lambda Sensor Timing Period",
  '2720': "Lambda Sensor Timing Switching Time",
  '2721': "Lambda Sensor Timing Post Cat Bank 1",
  '2722': "O2 sensor pre-cat, bank 2 (signal)",
  '2724': "O2 sensor post-cat, bank 2 (signal)",
  '2725': "Lambda Sensor Timing Bank 2- Period",
  '2726': "Lambda Sensor Timing Bank 2- Switching Time",
  '2727': "Lambda Sensor Timing Post Cat Bank 2",
  '272A': "Multiplicative mixture adaptation, bank 1 (limit reached)",
  '272B': "Multiplicative mixture adaptation, bank 2 (limit reached)",
  '272C': "Additive mixture adaptation, bank 1 (limit reached)",
  '272D': "Additive mixture adaptation, bank 2 (limit reached)",
  '2731': "Inlet camshaft control (VANOS)",
  '2734': "Throttle Valve Potentiometer 1- Signal Implausible to Mass Air Flow Sensor",
  '2735': "Throttle Valve Potentiometer 2- Signal Implausible to Mass Air Flow Sensor",
  '2737': "EWS anti-tamper protection",
  '2738': "Catalytic converter efficiency, bank 1",
  '2739': "Catalytic Converter Efficiency Bank 1",
  '273A': "Catalytic converter efficiency, bank 2",
  '273D': "Catalytic Converter Efficiency Bank 2",
  '2740': "Pedal Position Sensor 1- Voltage Supply",
  '2741': "Pedal Position Sensor 2- Voltage Supply",
  '2742': "Misfire detection, cyl 1",
  '2743': "Misfire detection, cyl 5",
  '2744': "Misfire detection, cyl 3",
  '2745': "Misfire detection, cyl 6",
  '2746': "Misfire detection, cyl 2",
  '2747': "Misfire detection, cyl 4",
  '274E': "Misfire detection, all cylinders",
  '2750': "Throttle controller (briefly jammed)",
  '2751': "Throttle controller (permanently jammed)",
  '2752': "Throttle Position Controller- Jamming",
  '2753': "Ignition coil, cyl 1",
  '2754': "Ignition coil, cyl 5",
  '2755': "Ignition coil, cyl 3",
  '2756': "Ignition coil, cyl 6",
  '2757': "Ignition coil, cyl 2",
  '2758': "Ignition coil, cyl 4",
  '2760': "Secondary air system, bank 1",
  '2761': "Secondary air system, bank 2",
  '2764': "Secondary air pump relay",
  '2765': "Secondary air solenoid valve (activation)",
  '2766': "Inlet camshaft sensor (signal duration)",
  '2767': "Exhaust camshaft sensor (signal duration)",
  '2768': "Inlet camshaft sensor (phase position)",
  '2769': "Throttle Actuator Spring Test",
  '276C': "Exhaust camshaft sensor (phase position)",
  '276D': "Tank venting system",
  '2770': "Secondary air mass-air-flow sensor",
  '2772': "Tank vent valve output stage",
  '2774': "CAN Message- Engine Shutdown Time",
  '2775': "Engine Torque Monitoring Level 2",
  '2776': "Multifunction Steering Wheel Interface",
  '2777': "DME Self Test: Monitoring AD Converter",
  '2778': "Clutch Switch",
  '2779': "DME Self Test RAM",
  '277A': "Brake Light Switch",
  '277B': "DME Self Test ROM",
  '277C': "DME Self Test RESET",
  '277D': "Battery Voltage",
  '277E': "Engine Torque Monitoring Level 1",
  '277F': "Crankshift Sensor Speed",
  '2780': "Crankshift Sensor Reference",
  '2781': "Camshaft sensor, intake",
  '2782': "Camshaft sensor, exhaust",
  '2783': "Mass air flow sensor",
  '2786': "Throttle valve potentiometer 1",
  '2787': "Throttle valve potentiometer 2",
  '2788': "Vehicle speed",
  '2789': "Rough running detection",
  '278A': "Ambient temperature sensor",
  '278B': "Engine coolant temperature sensor",
  '278C': "Intake air temperature sensor",
  '278D': "Radiator outlet temperature sensor",
  '278E': "Differertial Pressure Sensor- Intake Manifold",
  '278F': "Alternator (under-excitation)",
  '2790': "Radiator outlet temperature",
  '2791': "Throttle adaptation required",
  '2792': "Throttle Actuator Position Monitoring",
  '2793': "Throttle Actuator Control Range",
  '2794': "Throttle Actuator Activation",
  '2795': "Throttle Actuator Spring Test",
  '2796': "Throttle Actuator Test Lower Stop",
  '2797': "Throttle Actuator Booster Adjustment",
  '2798': "Throttle Actuator Emergency Operating Point",
  '2799': "Throttle Actuator Adaptation Aborted Environmental Conditions",
  '279A': "Throttle Actuator Relearn Abort",
  '279B': "Map Cooling Thermostat Mechanism",
  '279C': "Map Cooling Thermostat Output Stage",
  '279D': "Electric Fan Output Stage",
  '279E': "Exhaust Flap Output Stage",
  '27A0': "E-Box Fan Activation",
  '27A1': "Throttle- Starting Test",
  '27A4': "DME to EWS interface",
  '27A5': "Throttle Adaptation",
  '27A6': "Fuel injector, cyl 1",
  '27A7': "Fuel injector, cyl 5",
  '27A8': "Fuel injector, cyl 3",
  '27A9': "Fuel injector, cyl 6",
  '27AA': "Fuel injector, cyl 2",
  '27AB': "Fuel injector, cyl 4",
  '27B2': "Brake Light Switch- Signal",
  '27B3': "Throttle – Mass Air Flow Adjustment Plausibility",
  '27B4': "Ambient Pressure Sensor",
  '27B5': "Inlet Camshaft Control Output Stage",
  '27B7': "Fuel pump relay output stage",
  '27B8': "Differential Pressure Sensor Intake Manifold Plausibility",
  '27B9': "Lambda Sensor Pre Cat Bank 1- Voltage Excursion",
  '27BA': "Lambda Sensor Pre Cat Bank 2- Voltage Excursion",
  '27BB': "Exhaust Camshaft Control",
  '27BD': "Exhaust Camshaft Control Output Stage",
  '27C1': "All Camshaft Sensors Failed",
  '27C2': "A/C compressor control output stage",
  '27C3': "Oil level sensor",
  '27C4': "Main relay",
  '27C5': "Brake Light Test Switch- Signal",
  '27C7': "Main Relay Switching Time",
  '27CA': "DMTL Pump Motor- Activation",
  '27CC': "DMTL leakage",
  '27CD': "DMTL module failure",
  '27CE': "Load Monitoring",
  '27CF': "Firing Cyl 1",
  '27D0': "Firing Cyl 5",
  '27D1': "Firing Cyl 3",
  '27D2': "Firing Cyl 6",
  '27D3': "Firing Cyl 2",
  '27D4': "Firing Cyl 4",
  '27D6': "Idle Speed Control Valve- Activation – Position Closed",
  '27D7': "Idle Speed Control Valve- Activation – Position Open",
  '27D9': "DMTL Heater- Activation",
  '27DA': "Alternator BSD fault",
  '27DB': "Accelerator and brake pedal (signal)",
  '27DC': "EWS 3.3 Random Code Storage",
  '27DD': "Engine coolant temp sensor (gradient)",
  '27DE': "Engine coolant temp sensor (signal)",
  '27DF': "Engine Coolant Temp Sensor- Signal Constant",
  '27E0': "Crank Position Sensor- Segment Timing",
  '27E1': "Pedal Travel Sensor Monitoring",
  '27E2': "Knock sensor 1",
  '27E3': "Knock sensor 2",
  '27E6': "Knock Control Zero Test",
  '27E7': "Knock Control Offset",
  '27E8': "Knock Control Test Pulse",
  '27EB': "CAN message, EGS",
  '27EC': "CAN message EGS",
  '27ED': "CAN message, ASC/DSC",
  '27EE': "CAN message, instrument cluster",
  '27F2': "Tank fill level",
  '27F3': "CAN message Valvetronic Control Unit",
  '27F7': "Pedal Travel Sensor Potentiometer 1",
  '27F8': "Pedal Travel Sensor Potentiometer 2",
  '27FB': "Radiator Shutter",
  // 28xx
  '2800': "CAN message Instrument Cluster",
  '2804': "Cruise Control Request",
  '2805': "Cruise Control Switch Signal",
  '2806': "Cruise Control Data Transmission",
  '2807': "Throttle Position Sensor Implausible- 1 vs. 2",
  '2808': "Throttle Position Sensor Implausible- Ratio",
  '2809': "CAN message Instrument Cluster",
  '280B': "CAN message DSC",
  '280C': "CAN message DSC",
  '280D': "CAN message Steering Angle Sensor",
  '280E': "CAN message SMG",
  '280F': "CAN message DSC",
  '2811': "Local CAN Communication Error",
  '2812': "Oil temperature",
  '2813': "DME Monitoring Group A",
  '2814': "DME Monitoring Group B",
  '2815': "DME Monitoring Group C",
  '2816': "DME Monitoring Speed Sensor or ECU Fault",
  '281A': "CAN No Message TxU",
  '281C': "BSD interface signal",
  '281D': "BSD Signal",
  '281E': "DISA Intake System Output Stage",
  '2823': "Lambda Sensor Heater Pre Cat Bank 1",
  '2824': "Lambda Sensor Heater Pre Cat Bank 2",
  '2825': "Lambda Sensor Timing Bank 1",
  '2826': "Lambda Sensor Timing Bank 2",
  '282F': "CAN Communication Fault",
  '2830': "DME Self Test Checksum",
  '2831': "DME Self Test Processor Monitoring",
  '283A': "Oil condition sensor",
  '283D': "PT-CAN Communication Error",
  '283E': "Variable Valve Gear Output Stage Enable Line",
  '283F': "Oil Pressure Switch Implausibility",
  '2850': "Variable Valve Gear Guide Sensor",
  '2852': "Variable Valve Gear Reference Sensor",
  '2854': "Variable Valve Gear Plausibility Sensor",
  '2856': "Variable Valve Gear Voltage Supply",
  '2858': "Variable Valve Gear Adaptation Function",
  '285A': "Variable Valve Gear Servomotor Monitoring",
  '285C': "Variable Valve Gear CAN Communication",
  '285E': "Variable Valve Gear Control Unit Internal Fault",
  '2860': "Variable Valve Gear Servomotor Output Stage",
  '2862': "Variable Valve Gear Voltage Supply Power Output Stage",
  '2865': "Variable Valve Gear Torque Limitation- Limp Mode",
  '2866': "Variable Valve Gear Adaptation Needed",
  '2867': "Variable Valve Gear Overload",
  '286A': "DME Self Test- Knock Sensor Module",
  '286B': "DME Self Test- Multiple Output Module",
  '2882': "Fuel Trim Bank 1",
  '2883': "Fuel Trim Bank 2",
  '2892': "Misfiring",
  '2893': "Control Module Temperature",
  '2894': "Control Module Fault",
  '2895': "Crankshaft sensor (signal)",
  '2896': "Inlet camshaft sensor (signal)",
  '2897': "Exhaust camshaft sensor (signal)",
  '2898': "Lambda Sensor Post Cat- Bank 1 Signal",
  '2899': "Lambda Sensor Post Cat- Bank 2 Signal",
  '289A': "Lambda Sensor Heater Pre Cat- Bank 1 Function",
  '289B': "Lambda Sensor Heater Pre Cat- Bank 2 Function",
  '289C': "Lambda Sensor Heater Post Cat- Bank 1 Function",
  '289D': "Lambda Sensor Heater Post Cat- Bank 2 Function",
  '289E': "Lambda Sensor Pre Cat Bank 1",
  '289F': "Lambda Sensor Pre Cat Bank 2",
  '28A1': "Cruise Control -Monitoring",
  '28A2': "Air Flow -Monitoring",
  '28A4': "Engine Speed -Monitoring",
  '28A5': "Pedal Position Sensor -Monitoring",
  '28AA': "Idle Control -Monitoring",
  '28AB': "External Torque Request -Monitoring",
  '28AC': "Specified Torque -Monitoring",
  '28AD': "Actual Torque -Monitoring",
  '28B1': "Speed Limitation -Monitoring",
  '28B2': "Speed Limitation -Reset",
  '28B3': "Throttle -Continuous Adaptation",
  '28B4': "Button -Driving Dynamics Control",
  '28B5': "Sound Flap -Signal",
  '28B6': "Inlet Camshaft -Mechanical",
  '28B8': "Exhaust Camshaft -Mechanical",
  '28BA': "Inlet Camshaft -Stiff",
  '28BC': "Exhaust Camshaft -Stiff",
  '28BD': "Inlet Camshaft Sensor -Locking",
  '28BE': "Exhaust Camshaft Sensor -Locking",
  '28C1': "O2 sensor pre-cat, bank 1",
  '28C2': "O2 sensor pre-cat, bank 2",
  '28C3': "Lambda Sensor Heater Pre Cat Bank 1 Function",
  '28C4': "Lambda Sensor Heater Pre Cat Bank 2 Function",
  '28C5': "Lambda Sensor Post Cat Bank 1 System Check",
  '28C6': "Lambda Sensor Post Cat Bank 2 System Check",
  '28CA': "Ozone Conversion- Too Low",
  '28CB': "Ozone Sensor 2",
  '28CC': "Ozone Sensor 1",
  '28CF': "Fuel Pump- Emergency Shutoff",
  '28D0': "Fuel Pump- Monitoring",
  '28D6': "Process Error- Coding",
  '28D7': "Alternator Communication",
  '28D8': "RAM Backup",
  '28DB': "Variable Valve Gear Minimum Lift Adaptation Exceeded",
  '28DD': "Air Mass System",
  '28E6': "Evaluation Module Lambda Sensor Bank 1 On-board Diagnosis",
  '28E7': "Evaluation Module Lambda Sensor Bank 2 On-board Diagnosis",
  '28E8': "Lambda Sensor Bank 1 Trim Control",
  '28E9': "Lambda Sensor Bank 2 Trim Control",
  '28EA': "Lambda Sensor Post Cat Bank 1 Signal",
  '28EB': "Lambda Sensor Post Cat Bank 2 Signal",
  '28EC': "Lambda Sensor Post Cat Bank 1 Signal at Full Load",
  '28ED': "Lambda Sensor Post Cat Bank 2 Signal at Full Load",
  '28F0': "Lambda Sensor Post Cat Bank 1 System Check",
  '28F1': "Lambda Sensor Post Cat Bank 2 System Check",
  '28F2': "Lambda Sensor Bank 1 Trim Control",
  '28F3': "Lambda Sensor Bank 2 Trim Control",
  '28F4': "Lambda Sensor Pre Cat Bank 1 Cold Test",
  '28F5': "Lambda Sensor Pre Cat Bank 2 Cold Test",
  '28F6': "Lambda Sensor Post Cat Bank 1 Cold Test",
  '28F7': "Lambda Sensor Post Cat Bank 2 Cold Test",
  '28F9': "Rough Running- Segment Time Measurement",
  '28FA': "CAN Torque for Switching Phase",
  '28FB': "Active Cruise Control (ACC)",
  '28FF': "DME Self Test",
  // 29xx
  '2900': "DME Self Test",
  '2960': "Lambda Sensor Pre Cat Bank 1",
  '2961': "Lambda Sensor Pre Cat Bank 2",
  '2962': "Lambda Sensor Pre Cat Bank 1 Dynamics",
  '2963': "Lambda Sensor Pre Cat Bank 2 Dynamics",
  '2964': "Lambda Sensor Pre Cat Bank 1 Ceramic Temperature",
  '2965': "Lambda Sensor Pre Cat Bank 2 Ceramic Temperature",
  '2966': "Lambda Sensor Pre Cat Bank 1 Signal",
  '2967': "Lambda Sensor Pre Cat Bank 2 Signal",
  '296A': "Lambda Sensors Pre Cat Swapped",
  '296B': "Lambda Sensors Post Cat Swapped",
  '2972': "Jet Pump for Brake Servo",
  '2973': "Lambda Sensor Pre Cat Bank 1 Lines",
  '2974': "Lambda Sensor Pre Cat Bank 2 Lines",
  '2986': "Lambda Sensor Pre Cat Bank 1 System Check",
  '2987': "Lambda Sensor Pre Cat Bank 2 System Check",
  '2988': "Lambda Sensor Pre Cat Bank 1 System Check",
  '2989': "Lambda Sensor Pre Cat Bank 2 System Check",
  '299A': "CAN Fault Management EGS",
  '299B': "Battery Sensor",
  '299C': "Battery Sensor",
  '299D': "Battery Sensor",
  '299E': "Lambda Sensor Post Cat Bank 1 Signal",
  '299F': "Lambda Sensor Post Cat Bank 1 Signal",
  '29A0': "Lambda Sensor Post Cat Bank 2 Signal",
  '29A1': "Lambda Sensor Post Cat Bank 2 Signal",
  '29A2': "Lambda Sensor Pre Cat Bank 2 Signal",
  '29A3': "Lambda Sensor Pre Cat Bank 2 Signal",
  '29A4': "Lambda Sensor Heater Pre Cat Bank 1 Activation",
  '29A5': "Lambda Sensor Heater Pre Cat Bank 2 Activation",
  '29A6': "Lambda Sensor Pre Cat Bank 1 Signal",
  '29A7': "Lambda Sensor Pre Cat Bank 1 Signal",
  '29A8': "Power Management Vehicle Electrical System",
  '29A9': "Power Management Battery",
  '29AB': "Torque Request via CAN",
  '29AE': "Tank Cap",
  '29B5': "Aux Air System",
  '29B6': "Cylinder Cutout",
  '29CC': "Misfire Several Cylinders",
  '29CD': "Misfire Cyl 1",
  '29CE': "Misfire Cyl 2",
  '29CF': "Misfire Cyl 3",
  '29D0': "Misfire Cyl 4",
  '29DD': "Rough Running Detection",
  '29E5': "Mixture Adaptation 1 Air Density Upper Speed Range",
  '29E6': "Mixture Adaptation 2 Air Density Upper Speed Range",
  '29E7': "Mixture Adaptation 1 Air Leak",
  '29E8': "Mixture Adaptation 2 Air Leak",
  '29ED': "Mixture Adaptation 1 Air Density Lower Speed Range",
  '29EE': "Mixture Adaptation 2 Air Density Lower Speed Range",
  '29F4': "Catalytic Converter Efficiency 1",
  '29FE': "Aux Air System",
  '29FF': "Aux Air System",
  // 2Axx
  '2A03': "Aux Air Pump Relay",
  '2A19': "Tank Venting Valve",
  '2A59': "Valvetronic Eccentric Shaft Sensor 1",
  '2A5B': "Valvetronic Eccentric Shaft Sensor 1",
  '2A5D': "Valvetronic Eccentric Shaft Sensor 1",
  '2A5F': "Valvetronic Eccentric Shaft Sensor 1",
  '2A61': "Valvetronic Adaptation 1",
  '2A63': "Valvetronic Servomotor 1",
  '2A67': "Valvetronic Internal Fault",
  '2A69': "Valvetronic Voltage Supply Servomotor 1",
  '2A6B': "Valvetronic Power Limitation Servomotor",
  '2A6C': "Valvetronic Adaptation",
  '2A6D': "Valvetronic Electrical Overload Protection 1",
  '2A6F': "Valvetronic Minimum Lift Exceeded",
  '2A70': "Valvetronic Servomotor",
  '2A71': "Valvetronic Relief Relay",
  '2A80': "Inlet VANOS Activation 1",
  '2A83': "Inlet VANOS 1",
  '2A85': "Exhaust VANOS Activation 1",
  '2A88': "Exhaust VANOS 1",
  // 2Bxx
  '2B5C': "Crankshaft Sensor",
  '2B5D': "Crankshaft Sensor",
  '2B62': "Camshaft Sensor 1 Inlet",
  '2B63': "Camshaft Sensor 2 Exhaust",
  '2B66': "Camshaft Sensor",
  '2B70': "Variable Intake System",
  '2B7F': "Idle Speed Control",
  '2B80': "Idle Speed Control",
  '2B8A': "Control Module- Internal Fault Knock Control",
  '2B8B': "Control Module- Internal Fault Knock Control",
  '2B8C': "Control Module- Internal Fault Knock Control",
  '2B98': "Control Module- Internal Fault RAM",
  '2B99': "Control Module- Internal Fault RAM",
  '2B9A': "Control Module- Internal Fault RAM",
  '2B9B': "Control Module- Internal Fault ROM",
  '2B9C': "Control Module- Internal Fault Reset",
  '2BA7': "Engine Torque too High",
  // 2Cxx
  '2C24': "O2 sensors pre-cat Swapped",
  '2C45': "O2 sensor pre-cat 1",
  '2C46': "O2 sensor pre-cat 2",
  '2C6A': "O2 sensor post-cat Swapped",
  '2C6D': "O2 sensor post-cat 1 Timing",
  '2C6E': "O2 sensor post-cat 2 Timing",
  '2C6F': "O2 sensor post-cat 1",
  '2C70': "O2 sensor post-cat 2",
  '2C71': "O2 sensor post-cat 1",
  '2C72': "O2 sensor post-cat 2",
  '2C9C': "O2 sensor Heater pre-cat 1",
  '2C9D': "O2 sensor Heater pre-cat 2",
  '2CA0': "O2 sensor Heater pre-cat 1",
  '2CA1': "O2 sensor Heater pre-cat 2",
  '2CA2': "O2 sensor Heater pre-cat 1",
  '2CA3': "O2 sensor Heater pre-cat 2",
  '2CA8': "O2 sensor Heater post-cat 1",
  '2CA9': "O2 sensor Heater post-cat 2",
  '2CEF': "Throttle Valve Actuator",
  '2CF0': "Throttle Valve Actuator",
  '2CF1': "Throttle Valve Actuator",
  '2CF8': "Throttle Valve Potentiometer",
  '2CF9': "Throttle Valve Potentiometer 1",
  '2CFA': "Throttle Valve Potentiometer 2",
  '2CFF': "Throttle Valve Actuator",
  // 2Dxx
  '2D00': "Throttle Valve Actuator",
  '2D01': "Throttle Valve Actuator",
  '2D02': "Throttle Valve Actuator",
  '2D03': "Throttle Valve Actuator",
  '2D04': "Throttle Valve Actuator",
  '2D05': "Throttle Valve Actuator",
  '2D08': "Throttle Actuator",
  '2D0F': "Mass Air Flow Sensor Signal",
  '2D19': "Accelerator Pedal Module",
  '2D1A': "Accelerator Pedal Module",
  '2D1B': "Accelerator Pedal Module Signal 1",
  '2D1C': "Accelerator Pedal Module Signal 2",
  '2D28': "Intake Manifold Pressure Sensor Signal",
  '2D29': "Intake Manifold Pressure Sensor Plausibility",
  '2D6E': "Control Module Internal Fault Torque Monitoring",
  '2D6F': "Load Sensor Monitoring",
  '2D70': "Control Module Internal Fault",
  '2D71': "Control Module Internal Fault",
  '2D72': "Control Module Internal Fault",
  '2D73': "Fuel Pressure Sensor",
  '2D74': "Fuel Pressure Sensor",
  '2D75': "Crankshaft Sensor",
  '2D76': "Accelerator Pedal Module",
  // 2Exx
  '2E24': "Ignition Coil Cyl 1",
  '2E25': "Ignition Coil Cyl 2",
  '2E26': "Ignition Coil Cyl 3",
  '2E27': "Ignition Coil Cyl 4",
  '2E30': "Fuel Injector Cyl 1",
  '2E31': "Fuel Injector Cyl 2",
  '2E32': "Fuel Injector Cyl 3",
  '2E33': "Fuel Injector Cyl 4",
  '2E68': "Knock Sensor Signal 1",
  '2E69': "Knock Sensor Signal 2",
  '2E95': "Generator (alternator)",
  '2E97': "Generator (alternator)",
  '2EE0': "Engine Coolant Temperature Sensor Signal",
  '2EEA': "Radiator Outlet Temperature Sensor Signal",
  '2EF4': "Map Thermostat Mechanism Jammed",
  '2EF5': "Map Thermostat Activation",
  '2EFE': "Electric fan",
  // 2Fxx
  '2F08': "Intake Air Temperature Sensor Signal",
  '2F12': "A/C Compressor Relay",
  '2F17': "Engine oil temperature too high",
  '2F44': "EWS intervention",
  '2F45': "EWS Data Line",
  '2F46': "EWS Calibration",
  '2F4E': "Road speed signal",
  '2F62': "Brake light switch",
  '2F67': "Clutch switch",
  '2F76': "Control Module Internal Fault Ambient Pressure Sensor",
  '2F85': "Control module Internal fault Internal Temperature Sensor",
  '2F8A': "Power supply",
  '2F94': "Fuel Pump Relay Activation",
  '2F99': "External Temperature Sensor Plausibility",
  '2F9E': "Oil Level Sensor",
  '2FA3': "Coding Error",
  // 30xx
  '3000': "Brake Light or Brake Light Test Switch",
  '3005': "Voltage Supply KL15",
  // 35xx
  '3505': "Glow Plug System",
  '3506': "Glow Plug System 2",
  '3510': "DDE Main Relay",
  '3515': "A/C Power Output",
  '3520': "Engine Boost Actuation",
  '3565': "High Pressure Pump",
  '3580': "High Pressure Pump Shut Off Valve",
  '3596': "Brake Light Switch",
  // 36xx
  '3600': "Atmospheric Pressure Sensor",
  '3605': "Air Flow Meter HFM 1 or 2",
  '3610': "EGR System",
  '3615': "EGR System - Regulation",
  '3620': "Air Flow Meter HFM Signal",
  // 3Exx
  '3E90': "Crankshaft RPM - No Signal",
  '3E91': "Crankshaft RPM - Wrong Signal",
  '3E95': "Intake air Temperature Sensor",
  '3EA0': "Crankshaft Position Sensor",
  '3EA1': "Crankshaft Position Sensor",
  '3EA5': "Intake air Temperature Sensor",
  '3EA6': "Intake air Temperature Sensor",
  '3EB0': "RPM Calculation",
  '3EB5': "Air flow Sensor 2",
  '3EB6': "Air flow Sensor 2",
  '3EC0': "Camshaft Sensor - No Signal",
  '3EC1': "Camshaft Sensor - Wrong Signal",
  '3EC7': "Camshaft Sensor",
  '3ED0': "Camshaft Sensor - No Signal",
  '3ED1': "Camshaft Sensor - Wrong Signal",
  '3ED5': "Air Flow Sensor 2",
  '3ED6': "Air Flow Sensor 2",
  '3EDC': "Variant Coding",
  '3EDD': "Variant Coding",
  '3EE0': "Coolant Temperature Sensor - short circuit to B+ or Open",
  '3EE1': "Coolant Temperature Sensor - Short Circuit to B",
  '3EE2': "Coolant Temperature Sensor",
  '3EE3': "Coolant Temperature Sensor",
  '3EE5': "Air Mass Flow Sensor 2",
  '3EE6': "Air Mass Flow Sensor 2",
  '3EE7': "Air Mass Flow Sensor 2",
  '3EED': "Power Management Closed Circuit Current",
  '3EF3': "Coolant Temperature Sensor not Plausible",
  '3EF5': "Intake Air Temperature Sensor 2 (HFM Reference Signal)",
  '3EF6': "Intake Air Temperature Sensor 2 (HFM Reference Signal)",
  '3EF7': "Intake Air Temperature Sensor 2 (HFM Reference Signal)",
  '3EFB': "Thermal Oil Level Sensor",
  '3EFC': "Thermal Oil Level Sensor",
  '3EFD': "Thermal Oil Level Sensor",
  // 3Fxx
  '3F00': "Boost Pressure Sensor - short circuit to B+",
  '3F01': "Boost Pressure Sensor - Short circuit to B - or Open",
  '3F02': "Boost Pressure Sensor",
  '3F03': "Boost Pressure Sensor - Plausibility",
  '3F05': "MIL OFF",
  '3F10': "Pedal Position Sensor 1",
  '3F11': "Pedal Position Sensor 1 - Short circuit to B",
  '3F13': "Pedal Position Sensor 1 - Potentiometer Plausibility",
  '3F15': "MIL ON",
  '3F20': "Pedal Position Sensor 2",
  '3F21': "Pedal Position Sensor 2 - Short Circuit to B",
  '3F23': "Pedal Position Sensor 2 - Potentiometer Plausibility",
  '3F25': "Input Air Flow Control",
  '3F30': "Rail Pressure Sensor - short circuit to B+",
  '3F31': "Rail Pressure Sensor - Short Circuit to B",
  '3F35': "Input Air Flow Control at Idle Speed",
  '3F40': "Rail Pressure Sensor - Max for Compensation",
  '3F41': "Rail Pressure Sensor - Min for Compensation",
  '3F47': "Brake Light or Brake Light Test Switch",
  '3F48': "Brake Light or Brake Light Test Switch",
  '3F50': "Vehicle Speed Signal - Too High",
  '3F51': "Vehicle Speed Signal",
  '3F52': "Vehicle Speed Signal",
  '3F53': "Vehicle Speed Signal",
  '3F60': "Pedal Position Sensor Ref. VSS",
  '3F62': "Vehicle Speed Signal from CAN",
  '3F67': "Filling Pressure Modulator 2",
  '3F70': "Intake Air Temperature Sensor",
  '3F71': "Intake Air Temperature Sensor",
  '3F72': "Intake Air Temperature Sensor",
  '3F77': "Boost Pressure Modulator 1",
  '3F82': "Ambient Temp Sensor",
  '3F87': "Boost Pressure Modulator 2",
  '3F97': "Boost Pressure Modulator 1",
  '3FB0': "Air Flow Meter - Signal too High or short circuit to B+",
  '3FB1': "Air Flow Meter - Signal too Low or Short circuit to B",
  '3FB5': "Control master/slave",
  '3FB6': "Control master/slave",
  '3FB7': "Control Unit - Internal Master",
  '3FC0': "Air Flow Meter - Deviation too High at Idle Speed",
  '3FD0': "Air Flow Meter - Deviation too High",
  '3FE0': "Air Flow Meter",
  '3FE1': "Air Flow Meter",
  '3FF0': "Air Flow Meter",
  '3FF1': "Air Flow Meter",
  // 40xx
  '4000': "Fuel Temperature Sensor",
  '4001': "Fuel Temperature Sensor",
  '4010': "Exhaust Gas Pressure Sensor - short circuit to B+",
  '4011': "Exhaust Gas Pressure Sensor - Short Circuit to B",
  '4020': "EGT - short circuit to B+",
  '4021': "EGT - Short Circuit to B",
  '4030': "EGT Before Cat - short circuit to B+",
  '4031': "EGT Before Cat - Short Circuit to B",
  '4032': "Exhaust Gas Pressure Sensor",
  '4060': "Atmospheric Pressure Sensor DDE - short circuit to B+",
  '4061': "Atmospheric Pressure Sensor DDE - Short Circuit to B",
  '4062': "Atmospheric Pressure Sensor DDE",
  '4063': "Atmospheric Pressure Sensor DDE - Plausibility Ref. Boost",
  '4072': "Automatic Gearbox Switch Signal",
  '4080': "Brake Light or Brake Light Test Switch",
  '4082': "Brake Light or Brake Light Test Switch",
  '4083': "Brake Light or Brake Light Test Switch",
  '40A1': "Alternator Signal",
  '40E0': "Alternator",
  // 41xx
  '4100': "A/C Power Output",
  '4101': "A/C Power Output",
  '4102': "A/C Power Output",
  '4103': "A/C Power Output",
  '4108': "Control master/slave",
  '410C': "Swirl flap actuator",
  '4117': "Control master/slave",
  '4118': "Control master/slave",
  '4125': "Power supply",
  '4126': "Power supply",
  '4130': "Swirl flap - short circuit to B+",
  '4135': "Power supply",
  '4136': "Power supply",
  '4140': "Swirl flap",
  '4141': "Swirl flap - Short Circuit to B",
  '4145': "Power supply",
  '4146': "Power supply",
  '4152': "Swirl flap - open circuit",
  '4153': "Swirl flap - Plausibility, Overtemp of Output Stage",
  '4155': "Exhaust Flap Actuator",
  '4156': "Exhaust Flap Actuator",
  '4157': "Exhaust Flap Actuator",
  '4158': "Exhaust Flap Actuator",
  '4160': "Raise Pressure Pump - short circuit to B+",
  '4161': "Raise Pressure Pump - Short Circuit to B",
  '4162': "Raise Pressure Pump - Activation Interrupted",
  '4163': "Raise Pressure Pump - Plausibility, Overtemp of Output Stage",
  '4165': "DPF - Flow Resistance too High",
  '4166': "DPF - Flow Resistance too Low",
  '4175': "Exhaust gas temp Sensor before DPF",
  '4180': "Boost Pressure Actuator - short circuit to B+",
  '4185': "Exhaust gas temp Sensor before Cat",
  '4186': "Exhaust gas temp Sensor before Cat",
  '4188': "Exhaust gas temp Sensor before Cat",
  '4190': "Boost Pressure Actuator",
  '4191': "Boost Pressure Actuator - Short Circuit to B",
  '419A': "Atmospheric Pressure Sensor DDE",
  '419B': "Atmospheric Pressure Sensor DDE",
  '41A0': "Boost Pressure Actuator",
  '41A1': "Boost Pressure Actuator - Adjustment",
  '41A2': "Boost Pressure Actuator - open circuit",
  '41A3': "Boost Pressure Actuator - Plausibility, Overtemp of Output Stage",
  '41A6': "Message CBS Reset",
  '41A7': "Message CBS Reset",
  '41AA': "Boost Pressure Sensor",
  '41AB': "Boost Pressure Sensor",
  '41B0': "EGR - short circuit to B+",
  '41B5': "Transmission Fluid Temperature Sensor",
  '41BA': "Exhaust Backpressure Sensor",
  '41BB': "Exhaust Backpressure Sensor",
  '41C0': "Activation - Fan",
  '41C1': "Activation - Fan - Short Circuit to B",
  '41C2': "Activation - Fan - Activation Interrupted",
  '41C3': "Activation - Fan - Plausibility, Overtemp of Output Stage",
  '41CD': "Exhaust Backpressure Sensor - Plausibility",
  '41D0': "EGR Regulation",
  '41D1': "EGR - Short Circuit to B",
  '41D5': "O2 sensor Bias - short circuit to B+",
  '41D6': "O2 sensor Bias - Short Circuit to B",
  '41D7': "O2 sensor Bias - open circuit",
  '41E0': "EGR Regulation",
  '41E2': "EGR - open circuit",
  '41E3': "EGR - Plausibility, Overtemp of Output Stage",
  '41E5': "O2 sensor - short circuit to B+",
  '41E6': "O2 sensor - Short Circuit to B",
  '41E7': "O2 sensor - open circuit",
  '41F0': "Electric Ventilator - short circuit to B+",
  '41F1': "Electric Ventilator - Short Circuit to B",
  '41F2': "Electric Ventilator - Activation Interrupted",
  '41F3': "Electric Ventilator - Plausibility, Overtemp of Output Stage",
  '41F5': "O2 sensor Virtual Earth - short circuit to B+",
  '41F6': "O2 sensor Virtual Earth - Short Circuit to B",
  '41F7': "O2 sensor Virtual Earth - open circuit",
  // 42xx
  '4203': "Glow Module Communication",
  '4205': "O2 sensor Heating - short circuit to B+",
  '4206': "O2 sensor Heating - Short Circuit to B",
  '4207': "O2 sensor Heating",
  '420B': "EGR in Regen Mode",
  '4211': "Glow Plug Cyl 1 - short circuit to B+",
  '4212': "Glow Plug Cyl 1 - Activation Interrupted",
  '4213': "Glow Plug Cyl 1 - Plausibility, Overtemp of Output Stage",
  '4217': "O2 sensor",
  '4221': "Glow Plug Cyl 2 - short circuit to B+",
  '4222': "Glow Plug Cyl 2 - Activation Interrupted",
  '4223': "Glow Plug Cyl 2 - Plausibility, Overtemp of Output Stage",
  '4225': "O2 sensor - Signal",
  '4226': "O2 sensor - Signal too Low",
  '422A': "EGR in Regen Mode",
  '4231': "Glow Plug Cyl 3 - short circuit to B+",
  '4232': "Glow Plug Cyl 3 - Activation Interrupted",
  '4233': "Glow Plug Cyl 3 - Plausibility, Overtemp of Output Stage",
  '4235': "Control Unit Internal 21",
  '4236': "Control Unit Internal 21",
  '4241': "Glow Plug Cyl 4 - short circuit to B+",
  '4242': "Glow Plug Cyl 4 - Activation Interrupted",
  '4243': "Glow Plug Cyl 4 - Plausibility, Overtemp of Output Stage",
  '4245': "Control Unit Internal 22",
  '4246': "Control Unit Internal 22",
  '4251': "Glow Plug Cyl 5 - short circuit to B+",
  '4252': "Glow Plug Cyl 5 - Activation Interrupted",
  '4253': "Glow Plug Cyl 5 - Plausibility, Overtemp of Output Stage",
  '4258': "Control Unit Internal 23",
  '425D': "Accelerator Pedal Potentiometer Plausibility",
  '4261': "Glow Plug Cyl 6 - short circuit to B+",
  '4262': "Glow Plug Cyl 6 - Activation Interrupted",
  '4263': "Glow Plug Cyl 6 - Plausibility, Overtemp of Output Stage",
  '4267': "O2 sensor Shunt Detection",
  '4271': "Glow Plug Cyl 7 - short circuit to B+",
  '4272': "Glow Plug Cyl 7 - Activation Interrupted",
  '4273': "Glow Plug Cyl 7 - Plausibility, Overtemp of Output Stage",
  '4275': "O2 sensor Heater",
  '4276': "O2 sensor Heater",
  '4281': "Glow Plug Cyl 8 - short circuit to B+",
  '4282': "Glow Plug Cyl 8 - Activation Interrupted",
  '4283': "Glow Plug Cyl 8 - Plausibility, Overtemp of Output Stage",
  '4288': "O2 sensor Heater",
  '428B': "Boost Pressure Control of Large Turbo Control Deviation",
  '4293': "Control unit internal error 16",
  '4296': "O2 sensor",
  '4298': "O2 sensor",
  '429A': "Boost Pressure Control of Large Turbo Control Deviation",
  '42B5': "RPM Control",
  '42C0': "Oil Pressure Indicator Lamp - short circuit to B+",
  '42C1': "Oil Pressure Indicator Lamp - Short Circuit to B",
  '42C2': "Oil Pressure Indicator Lamp - Activation interrupted",
  '42C3': "Oil Pressure Indicator Lamp - Plausibility, Overtemp of Output Stage",
  '42D5': "Injector Cylinder 7",
  '42D6': "Injector Cylinder 7",
  '42D7': "Injector Cylinder 7",
  '42D8': "Injector Cylinder 7",
  '42E2': "Changeover Rail Pressure Control",
  '42F2': "Changeover Rail Pressure Control",
  '42F5': "Injector Cylinder 8",
  '42F6': "Injector Cylinder 8",
  '42F7': "Injector Cylinder 8",
  '42F8': "Injector Cylinder 8",
  // 43xx
  '4302': "Quantity Regulation Valve - Activation interrupted",
  '4303': "Quantity Regulation Valve - Plausibility, Overtemp of Output Stage",
  '4310': "Quantity Regulation Valve - short circuit to B+",
  '4321': "Quantity Regulation Valve - Short Circuit to B",
  '4332': "Rail Pressure Regulation Valve - Activation Interrupted",
  '4340': "Rail Pressure Regulation Valve - short circuit to B+",
  '4351': "Rail Pressure Regulation Valve - Short Circuit to B",
  '4360': "Rail Pressure Regulation Valve - Current Regulation",
  '4361': "Rail Pressure Regulation Valve - Current Regulation",
  '4362': "Rail Pressure Regulation Valve - Current Regulation",
  '4373': "Air Flow Mass not Plausible",
  '4378': "Rail Pressure Regulation Valve - Defect",
  '4382': "Rail Pressure Valve Position Test",
  '4390': "Boost Air Temperature Sensor - short circuit to B+",
  '4391': "Boost Air Temperature Sensor - Short Circuit to B",
  '4392': "Boost Air Temperature Sensor",
  '4397': "Position Test Volume Adjust Valve",
  '43A0': "Start - block Relay",
  '43A1': "Start - block Relay",
  '43A2': "Start - block Relay",
  '43A3': "Start - block Relay",
  '43C0': "Throttle Valve Actuator - short circuit to B+",
  '43D1': "Throttle Valve Actuator - Short Circuit to B",
  '43E2': "Throttle Valve Actuator - open circuit",
  '43E3': "Throttle Valve Actuator - Plausibility, Overtemp of Output Stage",
  '43F0': "Electrical Aux Heater - short circuit to B+",
  '43F1': "Electrical Aux Heater - Short Circuit to B",
  '43F2': "Electrical Aux Heater - Activation Interrupted",
  '43F3': "Electrical Aux Heater - Plausibility, Overtemp of Output Stage",
  // 44xx
  '4403': "Control unit internal error 17",
  '4410': "Injector Cylinder 1 - Activation",
  '4411': "Injector Cylinder 1 - Activation",
  '4412': "Injector Cylinder 1 - Activation",
  '4413': "Injector Cylinder 1 - Activation",
  '4417': "Control master/slave",
  '441C': "Injector Cylinder 1 - Earth Side Activation or open circuit",
  '4420': "Injector Cylinder 2 - Activation",
  '4421': "Injector Cylinder 2 - Activation",
  '4422': "Injector Cylinder 2 - Activation",
  '4423': "Injector Cylinder 2 - Activation",
  '4428': "Control master/slave",
  '442C': "Injector Cylinder 2 - Earth Side Activation or open circuit",
  '4430': "Injector Cylinder 3 - Activation",
  '4431': "Injector Cylinder 3 - Activation",
  '4432': "Injector Cylinder 3 - Activation",
  '4433': "Injector Cylinder 3 - Activation",
  '4438': "Control master/slave",
  '443C': "Injector Cylinder 3 - Earth Side Activation or open circuit",
  '4440': "Injector Cylinder 4 - Activation",
  '4441': "Injector Cylinder 4 - Activation",
  '4442': "Injector Cylinder 4 - Activation",
  '4443': "Injector Cylinder 4 - Activation",
  '444C': "Injector Cylinder 4 - Earth Side Activation or open circuit",
  '4450': "Injector Cylinder 5 - Activation",
  '4451': "Injector Cylinder 5 - Activation",
  '4452': "Injector Cylinder 5 - Activation",
  '4453': "Injector Cylinder 5 - Activation",
  '445C': "Injector Cylinder 5 - Earth Side Activation or open circuit",
  '4460': "Injector Cylinder 6 - Activation",
  '4461': "Injector Cylinder 6 - Activation",
  '4462': "Injector Cylinder 6 - Activation",
  '4463': "Injector Cylinder 6 - Activation",
  '446C': "Injector Cylinder 6 - Earth Side Activation or open circuit",
  '4473': "Control unit internal error 18",
  '4480': "Control unit internal error 19",
  '4491': "Control unit internal error 20",
  '44A0': "Injectors: Activation Cylinder. 1, 2, 3",
  '44A1': "Injectors: Activation Cylinder. 1, 2, 3",
  '44A3': "Injectors: Activation Cylinder. 1, 2, 3",
  '44AC': "Injectors: Activation Cylinder. 1, 2, 3",
  '44B0': "Injectors: Activation Cylinder. 1, 2, 3",
  '44B1': "Injectors: Activation Cylinder. 4, 5, 6",
  '44B3': "Injectors: Activation Cylinder. 4, 5, 6",
  '44BC': "Injectors: Activation Cylinder. 4, 5, 6",
  '44C0': "Number of Requested Injections Limited",
  '44C1': "Number of Requested Injections Limited",
  '44C2': "Number of Requested Injections Limited",
  '44D0': "Alternator",
  '44D2': "Alternator",
  '44D3': "Alternator",
  '44E2': "Alternator",
  '44E3': "Alternator",
  '44F0': "Rail Pressure not Plausible",
  // 45xx
  '4500': "EGR - Deviation",
  '4501': "EGR - Negative Deviation or Air Mass too High",
  '4506': "EGR - Deviation",
  '4507': "EGR - Posative Deviation or Air Mass too Low",
  '4512': "Thermal Oil Level Sensor",
  '4513': "Thermal Oil Level Sensor",
  '4521': "Boost Pressure Actuator - Regulation Pressure too High",
  '452A': "DPF System",
  '4530': "Boost Pressure Actuator - Regulation Pressure too Low",
  '4536': "Power Management",
  '453B': "PT Can Bus",
  '453C': "PT Can Bus",
  '453D': "PT Can Bus",
  '4541': "Thermal Oil Level Sensor",
  '454B': "Private CAN bus(master)",
  '454C': "Private CAN bus(master)",
  '454D': "Private CAN bus(master)",
  '4550': "Boost Pressure Modulation 2",
  '4560': "Rail Pressure Sensor - Plausibility - Pressure too Low",
  '4570': "Rail Pressure not Plausible",
  '4580': "Rail Pressure Sensor - Plausibility - Pressure too High",
  '4587': "Fuel Filter",
  '4590': "Rail Pressure not Plausible",
  '45A0': "Rail Pressure Sensor - Plausibility - Pressure too High",
  '45A5': "Boost Air Temp Sensor 2 - Signal",
  '45A6': "Boost Air Temp Sensor 2 - Signal",
  '45C0': "Rail Pressure not Plausible",
  '45E3': "Control master/slave",
  '45F2': "Control master/slave",
  '45F3': "Control master/slave",
  // 46xx
  '4600': "Rail Pressure Sensor - Plausibility - Pressure too Low",
  '4605': "DPF System",
  '4610': "Rail Pressure not Plausible",
  '4618': "DPF - Plausibility - Pressure Reference",
  '4620': "Rail Pressure Sensor - Plausibility - Pressure too High",
  '4628': "DPF System",
  '4630': "Rail Pressure not Plausible",
  '4640': "Rail Pressure not Plausible",
  '4645': "EGR Controller",
  '4650': "Rail Pressure not Plausible",
  '4656': "Control Unit Internal 24",
  '4660': "Power supply",
  '4661': "Power supply",
  '4665': "DPF Bank 1",
  '4666': "DPF Bank 1",
  '4667': "DPF Bank 1",
  '4670': "Power supply 1 - short circuit to B+",
  '4671': "Power supply 1 - Short Circuit to B",
  '4677': "Throttle Valve Actuator",
  '4680': "Power supply 2 - short circuit to B+",
  '4681': "Power supply 2 - Short Circuit to B",
  '4687': "Throttle Valve Actuator",
  '4690': "Power supply",
  '4691': "Power supply",
  '4697': "Throttle Valve Actuator",
  '46A0': "Control unit internal error 1",
  '46A1': "Control unit internal error 1",
  '46A2': "Control unit internal error 1",
  '46A3': "Control unit internal error 1",
  '46A7': "Swirl flap Actuator",
  '46B0': "Control unit internal error 2",
  '46B1': "Control unit internal error 2",
  '46B2': "Control unit internal error 2",
  '46B3': "Control unit internal error 2",
  '46B7': "Swirl flap Actuator",
  '46C0': "Control unit internal error 3",
  '46C1': "Control unit internal error 3",
  '46C2': "Control unit internal error 3",
  '46C3': "Control unit internal error 3",
  '46C7': "Swirl flap Actuator",
  '46D0': "Control unit internal error 4",
  '46D1': "Control unit internal error 4",
  '46D2': "Control unit internal error 4",
  '46D3': "Control unit internal error 4",
  '46D5': "Compressor Bypass Activation",
  '46D6': "Compressor Bypass Activation",
  '46D7': "Compressor Bypass Activation",
  '46D8': "Compressor Bypass Activation",
  '46E0': "Control unit internal error 5",
  '46E1': "Control unit internal error 5",
  '46E2': "Control unit internal error 5",
  '46E3': "Control unit internal error 5",
  '46E5': "Wastegate Valve Activation",
  '46E6': "Wastegate Valve Activation",
  '46F0': "Control unit internal error 6",
  '46F1': "Control unit internal error 6",
  '46F2': "Control unit internal error 6",
  '46F3': "Control unit internal error 6",
  // 47xx
  '4700': "Control unit internal error 7",
  '4701': "Control unit internal error 7",
  '4702': "Control unit internal error 7",
  '4703': "Control unit internal error 7",
  '4707': "Wastegate Valve Activation",
  '4708': "Wastegate Valve Activation",
  '4710': "Control unit internal error 8",
  '4711': "Control unit internal error 8",
  '4712': "Control unit internal error 8",
  '4713': "Control unit internal error 8",
  '4720': "Control unit internal error 9",
  '4721': "Control unit internal error 9",
  '4722': "Control unit internal error 9",
  '4723': "Control unit internal error 9",
  '4730': "Quantity Regulation Current Regulation",
  '4731': "Quantity Regulation Current Regulation",
  '4732': "Quantity Regulation Current Regulation",
  '4740': "Control unit internal error 11",
  '4747': "Injectors - Amplifier Adjustment(control-unit internal)",
  '4750': "Control unit internal error 12",
  '4753': "Control unit internal error 12",
  '475A': "Exhaust Backpressure Sensor - Bank 2",
  '475B': "Exhaust Backpressure Sensor - Bank 2",
  '4763': "Control unit internal error 13",
  '4765': "Injector Cyl 1 - Activation",
  '4766': "Injector Cyl 1 - Activation",
  '4767': "Injector Cyl 1 - Activation",
  '4768': "Injector Cyl 1 - Activation",
  '476A': "Injector Cyl 4/5/6 Buffer Voltage Measurement(control-unit internal)",
  '476B': "Injector Cyl 4/5/6 Buffer Voltage Measurement(control-unit internal)",
  '4770': "Control unit internal error 14",
  '4771': "Control unit internal error 14",
  '4772': "Control unit internal error 14",
  '4773': "Control unit internal error 14",
  '477C': "Injectors Activation Duration(control-unit internal)",
  '4780': "Control unit internal error 15",
  '4781': "Control unit internal error 15",
  '4782': "Control unit internal error 15",
  '4783': "Control unit internal error 15",
  '4785': "Injector Cyl 2 - Activation",
  '4786': "Injector Cyl 2 - Activation",
  '4787': "Injector Cyl 2 - Activation",
  '4788': "Injector Cyl 2 - Activation",
  '478C': "Injector Activation Duration(control-unit internal)",
  '4792': "Monitoring master/slave",
  '4793': "Monitoring master/slave",
  '4795': "Injector Cyl 3 - Activation",
  '4796': "Injector Cyl 3 - Activation",
  '4797': "Injector Cyl 3 - Activation",
  '4798': "Injector Cyl 3 - Activation",
  '47A5': "Injector Cyl 4 - Activation",
  '47A6': "Injector Cyl 4 - Activation",
  '47A7': "Injector Cyl 4 - Activation",
  '47A8': "Injector Cyl 4 - Activation",
  '47AB': "Private CAN Bus(Slave)",
  '47AC': "Private CAN Bus(Slave)",
  '47AD': "Private CAN Bus(Slave)",
  '47B5': "Injector Cyl 5 - Activation",
  '47B6': "Injector Cyl 5 - Activation",
  '47B7': "Injector Cyl 5 - Activation",
  '47B8': "Injector Cyl 5 - Activation",
  '47BB': "Power Train CAN Bus(Slave)",
  '47BC': "Power Train CAN Bus(Slave)",
  '47BD': "Power Train CAN Bus(Slave)",
  '47C5': "Injector Cyl 6 - Activation",
  '47C6': "Injector Cyl 6 - Activation",
  '47C7': "Injector Cyl 6 - Activation",
  '47C8': "Injector Cyl 6 - Activation",
  '47D5': "Injector Cyl 7 - Activation",
  '47D6': "Injector Cyl 7 - Activation",
  '47D7': "Injector Cyl 7 - Activation",
  '47D8': "Injector Cyl 7 - Activation",
  '47E5': "Injector Cyl 8 - Activation",
  '47E6': "Injector Cyl 8 - Activation",
  '47E7': "Injector Cyl 8 - Activation",
  '47E8': "Injector Cyl 8 - Activation",
  // 48xx
  '4803': "Torque Control ACC",
  '480A': "DPF - Bank 1",
  '4810': "Torque Control ACC",
  '481A': "DPF - Bank 1",
  '4830': "Intake Air Temperature Sensor",
  '4831': "Intake Air Temperature Sensor",
  '483D': "Throttle Actuator",
  '4841': "EGR Regulation 2",
  '484A': "Accelerator Pedal Potentiometer - Signal",
  '4850': "EGR Regulation 2",
  '4857': "Swirl flap Actuator",
  '4863': "Vehicle Speed Regulation",
  '4867': "Swirl flap Actuator",
  '486D': "Control Unit Software Fault",
  '4877': "Swirl flap Actuator",
  '487A': "O2 sensor Bank 2 - Bias Voltage",
  '487B': "O2 sensor Bank 2 - Bias Voltage",
  '487C': "O2 sensor Bank 2 - Bias Voltage",
  '4887': "Swirl flap Actuator",
  '488A': "O2 sensor Bank 2 - Pump Current",
  '488B': "O2 sensor Bank 2 - Pump Current",
  '488C': "O2 sensor Bank 2 - Pump Current",
  '4896': "Swirl flap Actuator",
  '489A': "O2 sensor Bank 2 - Virtual Ground",
  '489B': "O2 sensor Bank 2 - Virtual Ground",
  '489C': "O2 sensor Bank 2 - Virtual Ground",
  '48A2': "CAN Communication with ASC",
  '48A3': "CAN Communication with ASC",
  '48B2': "CAN Communication with ASC",
  '48B3': "CAN Communication with ASC",
  '48B5': "Injectors Voltage Measurement(control-unit internal)",
  '48B6': "Injectors Voltage Measurement(control-unit internal)",
  '48B7': "Injectors Voltage Measurement(control-unit internal)",
  '48BC': "O2 sensor Bank 2",
  '48C2': "CAN Communication with EGS",
  '48C5': "Injectors Voltage Measurement(control-unit internal)",
  '48C6': "Injectors Voltage Measurement(control-unit internal)",
  '48C7': "Injectors Voltage Measurement(control-unit internal)",
  '48CA': "O2 sensor Bank 2",
  '48CB': "O2 sensor Bank 2",
  '48D2': "CAN Communication with Instrument Cluster",
  '48D3': "CAN Communication with Instrument Cluster",
  '48DA': "Control Unit Internal 25",
  '48DB': "Control Unit Internal 25",
  '48EA': "Control Unit Internal 26",
  '48EB': "Control Unit Internal 26",
  '48F2': "CAN BUS Hardware",
  '48F3': "CAN BUS Hardware",
  '48F7': "Injectors Wiring Loom",
  '48FD': "Control Unit Internal 27",
  // 49xx
  '4900': "DSC Torque Intervention",
  '4907': "Injectors Selector Switch(control-unit internal)",
  '490B': "Control Unit Internal 28",
  '4912': "CAN BUS Hardware Defect in Operation",
  '4913': "CAN BUS Hardware Fault in Initialisation",
  '4917': "Injectors Charge Switch(control-unit internal)",
  '4920': "Transmission Link",
  '4925': "Throttle Valve Actuator 2 Activation",
  '492A': "O2 sensor Bank 2 Heater",
  '492B': "O2 sensor Bank 2 Heater",
  '4936': "Throttle Valve Actuator 2 Activation",
  '493D': "O2 sensor Bank 2",
  '4947': "Throttle Valve Actuator 2 Activation",
  '4948': "Throttle Valve Actuator 2 Activation",
  '494D': "O2 sensor Bank 2",
  '4957': "Throttle Valve Actuator 2",
  '495A': "Exhaust Temp Sensor before DPF Bank 2",
  '495B': "Exhaust Temp Sensor before DPF Bank 2",
  '4967': "Throttle Valve Actuator 2",
  '496A': "DPF Bank 2",
  '497A': "DPF Bank 2",
  '4991': "Message : Instrument Cluster",
  '4992': "Message : Instrument Cluster",
  '4997': "Throttle Valve Actuator 2",
  '49A2': "Message : Ambient Temperature",
  '49B0': "Message : Torque Request",
  '49C0': "Message : Torque Request",
  '49D2': "Message : Torque Request",
  '49E0': "Message : Torque Request",
  '49E7': "Throttle Actuator",
  '49F2': "Message : Vehicle Speed",
  '49F3': "Message : Vehicle Speed",
  // 4Axx
  '4A02': "Terminal 15",
  '4A03': "Terminal 15",
  '4A07': "Alternator",
  '4A08': "Alternator",
  '4A10': "BSD Interface",
  '4A13': "BSD Interface",
  '4A15': "Alternator",
  '4A17': "Alternator",
  '4A18': "Alternator",
  '4A22': "Boost Air Pressure Actuator 2 Activation",
  '4A23': "Boost Air Pressure Actuator 2 Activation",
  '4A25': "Intelligent Battery Sensor",
  '4A27': "Intelligent Battery Sensor",
  '4A28': "Intelligent Battery Sensor",
  '4A30': "Multifunction Steering Wheel - Toggle Bit",
  '4A31': "Multifunction Steering Wheel - Frequency Counter",
  '4A32': "Multifunction Steering Wheel - No Signal",
  '4A33': "Multifunction Steering Wheel - Signal not Plausible",
  '4A35': "Intelligent Battery Sensor",
  '4A37': "Intelligent Battery Sensor",
  '4A38': "Intelligent Battery Sensor",
  '4A41': "EWS Interface",
  '4A42': "EWS Interface",
  '4A43': "EWS Interface",
  '4A45': "Intelligent Battery Sensor",
  '4A47': "Intelligent Battery Sensor",
  '4A48': "Intelligent Battery Sensor",
  '4A50': "EWS Code Storage",
  '4A51': "EWS Code Storage",
  '4A56': "Power Management Battery",
  '4A58': "Power Management Battery",
  '4A60': "EWS Manipulation",
  '4A61': "EWS Manipulation",
  '4A62': "EWS Manipulation",
  '4A63': "EWS Manipulation",
  '4A65': "Power Management Vehicle Electrical System",
  '4A66': "Power Management Vehicle Electrical System",
  '4A67': "Power Management Vehicle Electrical System",
  '4A70': "Reference Values Incorrect",
  '4A80': "Intake Air Hose",
  '4AA2': "CAN Communication with EGS",
  '4AA3': "CAN Communication with EGS",
  '4AB0': "Electrical Aux Heater",
  '4AD5': "Zero Quantity Adaptation Injector 1",
  '4AD6': "Zero Quantity Adaptation Injector 1",
  '4AE0': "E - Box Ventilator - short circuit to B+",
  '4AE1': "E - Box Ventilator - Short circuit to B",
  '4AE2': "E - Box Ventilator - Activation Interrupted",
  '4AE3': "E - Box Ventilator - Plausibility, Overtemp of Output Stage",
  '4AE5': "Zero Quantity Adaptation Injector 2",
  '4AE6': "Zero Quantity Adaptation Injector 2",
  '4AF0': "Control Unit Temperature Sensor",
  '4AF1': "Control Unit Temperature Sensor",
  '4AF5': "Zero Quantity Adaptation Injector 3",
  '4AF6': "Zero Quantity Adaptation Injector 3",
  // 4Bxx
  '4B00': "Control Unit Temperature",
  '4B05': "Zero Quantity Adaptation Injector 4",
  '4B06': "Zero Quantity Adaptation Injector 4",
  '4B10': "Smooth Running Regulation - Correction Quantity too High",
  '4B11': "Smooth Running Regulation - Correction Quantity too Low",
  '4B15': "Zero Quantity Adaptation Injector 5",
  '4B16': "Zero Quantity Adaptation Injector 5",
  '4B20': "Electro ventilator - Blocked",
  '4B22': "Electro Ventilator",
  '4B25': "Zero Quantity Adaptation Injector 6",
  '4B26': "Zero Quantity Adaptation Injector 6",
  '4B35': "Oil Sensor",
  '4B36': "Oil Sensor",
  '4B37': "Oil Sensor",
  '4B38': "Oil Sensor",
  '4B45': "Injector Cyl 1 Energy Consumption Measurement",
  '4B50': "Quantity Compensation",
  '4B55': "Injector Cyl 2 Energy Consumption Measurement",
  '4B60': "Quantity Compensation",
  '4B65': "Injector Cyl 3 Energy Consumption Measurement",
  '4B75': "Injector Cyl 4 Energy Consumption Measurement",
  '4B80': "Rail Pressure not Plausible",
  '4B85': "Injector Cyl 5 Energy Consumption Measurement",
  '4B90': "Rail Pressure Control at Engine Start",
  '4B95': "Injector Cyl 6 Energy Consumption Measurement",
  '4BA0': "Intake Air Temperature Sensor - Signal too High or Short",
  '4BA1': "Intake Air Temperature Sensor - Signal too Low",
  '4BB0': "Air Flow Sensor power supply",
  '4BB1': "Air Flow Sensor power supply",
  '4BB5': "Air Flow Meter - Signal too Low",
  '4BB6': "Air Flow Meter - Signal too High",
  '4BC0': "Air Flow Meter - Signal too Low",
  '4BC1': "Air Flow Meter - Signal too High",
  '4BC2': "Air Flow Meter - Short Circuit",
  '4BC5': "Intake Air Temperature Sensor",
  '4BC6': "Intake Air Temperature Sensor",
  '4BC7': "Intake Air Temperature Sensor",
  '4BD2': "ARS Torque Request",
  '4BD5': "Engine Support",
  '4BD6': "Engine Support",
  '4BD7': "Engine Support",
  '4BD8': "Engine Support",
  '4BE2': "Message : Transmission data",
  '4BE7': "Message : Transmission data 2",
  '4BF2': "Message : Air Conditioning",
  '4BF7': "Message : Range",
  // 4Cxx
  '4C00': "Message : Cruise Control",
  '4C01': "Message : Cruise Control",
  '4C02': "Message : Cruise Control",
  '4C06': "Message : ARS Status",
  '4C07': "Message : ARS Status",
  '4C12': "Message : DSC Status",
  '4C15': "Message : Terminal 15",
  '4C16': "Message : Terminal 15",
  '4C17': "Message : Terminal 15",
  '4C20': "Message : DSC Torque",
  '4C21': "Message : DSC Torque",
  '4C22': "Message : DSC Torque",
  '4C23': "Message : DSC Torque",
  '4C27': "Message : Vehicle Speed",
  '4C28': "Message : Vehicle Speed",
  '4C45': "Injector Cyl 7 Energy Consumption Measurement",
  '4C55': "Injector Cyl 8 Energy Consumption Measurement",
  '4C65': "Zero Quantity Adaptation Injector 7",
  '4C66': "Zero Quantity Adaptation Injector 7",
  '4C75': "Supply Voltage Air Mass Flow Sensor 2",
  '4C76': "Supply Voltage Air Mass Flow Sensor 2",
  '4C95': "Zero Quantity Adaptation Injector 8",
  '4C96': "Zero Quantity Adaptation Injector 8",
  '4CA2': "Message : Power Management",
  '4CB2': "Message : Power Management",
  '4CB3': "Message : Power Management",
  '4CF3': "DPF - Plausibility - Exhaust Gas Pressure",
  // 4Dxx
  '4D00': "Exhaust Backpressure Sensor Bank 1",
  '4D03': "Exhaust Backpressure Sensor Bank 1",
  '4D25': "Exhaust Temp Sensor before Catalytic Converter Bank 2",
  '4D26': "Exhaust Temp Sensor before Catalytic Converter Bank 2",
  '4D45': "Exhaust Temp Sensor before DPF Bank 2",
  '4D46': "Exhaust Temp Sensor before DPF Bank 2",
  '4D56': "DPF Bank 2",
  '4D65': "DPF System",
  '4D75': "DPF System",
  '4D81': "Boost Pressure Actuator 2 Activation",
  '4D98': "Exhaust Backpressure Sensor Bank 2",
  '4DA3': "Boost Pressure Control",
  '4DA5': "Exhaust Backpressure Sensor Bank 2",
  '4DA8': "Exhaust Backpressure Sensor Bank 2",
  '4DB0': "EGR Controller 2 Activation",
  '4DC1': "EGR Controller 2 Activation",
  '4DD2': "EGR Controller 2 Activation",
  '4DD3': "EGR Controller 2 Activation",
  '4DD5': "Exhaust Temp Sensor before DPF Bank 2",
  '4DE0': "Monitoring master/slave - Private CAN",
  '4DE1': "Monitoring master/slave - Private CAN",
  '4DE3': "Monitoring master/slave - Private CAN",
  '4DF0': "Message : Transmission Torque",
  '4DF1': "Message : Transmission Torque",
  '4DF2': "Message : Transmission Torque",
  '4DF3': "Message : Transmission Torque",
  '4DF5': "Exhaust Temp Sensor before DPF Bank 2",
  // 5Dxx
  '5D90': "Left Front Wheel Speed Sensor : Accident Recognition",
  '5D91': "Left Front Wheel Speed Sensor : Extrapolation",
  '5D92': "Left Front Wheel Speed Sensor : Periodical Control",
  '5D93': "Left Front Wheel Speed Sensor : Accident Recognition",
  '5D94': "Left Front Wheel Speed Sensor : Long Term Control",
  '5DA0': "Right Front Wheel Speed Sensor : Accident Recognition",
  '5DA1': "Right Front Wheel Speed Sensor : Extrapolation",
  '5DA2': "Right Front Wheel Speed Sensor : Periodical Control",
  '5DA3': "Right Front Wheel Speed Sensor : Accident Recognition",
  '5DA4': "Right Front Wheel Speed Sensor : Long Term Control",
  '5DB0': "Left Rear Wheel Speed Sensor : Accident Recognition",
  '5DB1': "Left Rear Wheel Speed Sensor : Extrapolation",
  '5DB2': "Left Rear Wheel Speed Sensor : Periodical Control",
  '5DB3': "Left Rear Wheel Speed Sensor : Accident Recognition",
  '5DB4': "Left Rear Wheel Speed Sensor : Long Term Control",
  '5DC0': "Right Rear Wheel Speed Sensor : Accident Recognition",
  '5DC1': "Right Rear Wheel Speed Sensor : Extrapolation",
  '5DC2': "Right Rear Wheel Speed Sensor : Periodical Control",
  '5DC3': "Right Rear Wheel Speed Sensor : Accident Recognition",
  '5DC4': "Right Rear Wheel Speed Sensor : Long Term Control",
  '5DF0': "Pump Motor",
  '5DF2': "Internal Error, Valve/ECU Hardware Error, ROM/RAM Check",
  '5DF4': "Power Supply too Low",
  '5DF5': "Control Unit Internal Error",
  '5DF7': "Power Supply too High",
  // 5Exx
  '5E00': "Tyre Test Active",
  '5E01': "Tyre Test Timeout",
  '5E02': "Tyre Test Gyration Sensor Justification Error",
  '5E03': "Tyre Test Gyration Sensor Error",
  '5E04': "Tyre Test Lateral Acceleration Sensor Error",
  '5E05': "Tyre test Lateral Acceleration Sensor Error and Gyration Sensor",
  '5E06': "Tyre Test Gyration Sensor Fault",
  '5E07': "Tyre Test Lateral Acceleration Sensor Error and Gyration Sensor Fault",
  '5E08': "Tyre Test Steering Angle Sensor Error",
  '5E11': "Internal Error CAN-Controller",
  '5E14': "CAN Timeout DME/DDE",
  '5E15': "CAN Timeout EGS",
  '5E16': "CAN Timeout Instrument Cluster",
  '5E18': "CAN DME/DDE Message",
  '5E19': "CAN DME/DDE Torque Reduction Not Possible",
  '5E1A': "CAN DME/DDE Signal Error",
  '5E1E': "CAN Timeout LWS",
  '5E1F': "Steering Angle Sensor – not Initialised",
  '5E20': "Pressure Sensor 1 Accident Recognition",
  '5E21': "Pressure Sensor 2 Accident Recognition",
  '5E24': "Pressure Sensor 1/2 not Plausible",
  '5E26': "Sensor Power Supply",
  '5E2F': "Temperature Sensor",
  '5E30': "Lateral Acceleration Sensor Accident Recognition",
  '5E32': "Lateral Acceleration Signal not Plausible",
  '5E38': "Wheel Speed Sensor Accident Recognition",
  '5E3C': "Wheel Speed not Plausible",
  '5E40': "Lateral Acceleration Signal not Plausible, Offset",
  '5E43': "Lateral Acceleration Internal Error",
  '5E4E': "DSC Sensor Offset Check",
  '5E4F': "Long Time Regulation DSC",
  '5E59': "Coding Error",
  '5E5B': "Switch Pressed Longer than 10s or Faulty",
  '5E5D': "Brake Fluid Level Switch",
  '5E5E': "Brake Light Switch",
  // 70xx
  '7073': "Automatic Gearbox Switch Signal",
  // CDxx
  'CD87': "CAN Bus Communication Error",
  'CD8B': "CAN Bus - Control Module has Left the Bus",
};
