// hex DTC to English. keyed by BMW fault number (first token of F_ORT_TEXT, e.g.
// "27DA"). from BMW DME/DDE/ABS reference, beats word-by-word F_ORT_TEXT. used by
// deGerman(). covers ME9/MS45 (27xx, 28xx) E46/M54 engine codes plus body ranges.
window.BMW_FAULT_DB = {
  // ME9/MS45 engine (27xx), M54 DME range
  '2712': 'DMTL solenoid valve activation',
  '2713': 'Pre-cat lambda sensors swapped',
  '2714': 'O2 sensor heater, post-cat, bank 2',
  '2715': 'O2 sensor heater, pre-cat, bank 2',
  '2716': 'O2 sensor heater, post-cat, bank 1',
  '2718': 'Crankshaft sensor reference',
  '2719': 'Crankshaft sensor period',
  '271A': 'O2 sensor pre-cat, bank 1 (signal)',
  '271C': 'O2 sensor post-cat, bank 1 (signal)',
  '271D': 'O2 sensor heater, pre-cat, bank 1',
  '271E': 'O2 sensor heater, post-cat, bank 1',
  '2722': 'O2 sensor pre-cat, bank 2 (signal)',
  '2724': 'O2 sensor post-cat, bank 2 (signal)',
  '272A': 'Multiplicative mixture adaptation, bank 1 (limit reached)',
  '272B': 'Multiplicative mixture adaptation, bank 2 (limit reached)',
  '272C': 'Additive mixture adaptation, bank 1 (limit reached)',
  '272D': 'Additive mixture adaptation, bank 2 (limit reached)',
  '2731': 'Inlet camshaft control (VANOS)',
  '2737': 'EWS anti-tamper protection',
  '2738': 'Catalytic converter efficiency, bank 1',
  '273A': 'Catalytic converter efficiency, bank 2',
  '2742': 'Misfire detection, cyl 1',
  '2743': 'Misfire detection, cyl 5',
  '2744': 'Misfire detection, cyl 3',
  '2745': 'Misfire detection, cyl 6',
  '2746': 'Misfire detection, cyl 2',
  '2747': 'Misfire detection, cyl 4',
  '274E': 'Misfire detection, all cylinders',
  '2750': 'Throttle controller (briefly jammed)',
  '2751': 'Throttle controller (permanently jammed)',
  '2753': 'Ignition coil, cyl 1',
  '2754': 'Ignition coil, cyl 5',
  '2755': 'Ignition coil, cyl 3',
  '2756': 'Ignition coil, cyl 6',
  '2757': 'Ignition coil, cyl 2',
  '2758': 'Ignition coil, cyl 4',
  '2760': 'Secondary air system, bank 1',
  '2761': 'Secondary air system, bank 2',
  '2764': 'Secondary air pump relay',
  '2765': 'Secondary air solenoid valve (activation)',
  '2766': 'Inlet camshaft sensor (signal duration)',
  '2767': 'Exhaust camshaft sensor (signal duration)',
  '2768': 'Inlet camshaft sensor (phase position)',
  '276C': 'Exhaust camshaft sensor (phase position)',
  '276D': 'Tank venting system',
  '2770': 'Secondary air mass-air-flow sensor',
  '2772': 'Tank vent valve output stage',
  '2781': 'Camshaft sensor, intake',
  '2782': 'Camshaft sensor, exhaust',
  '2783': 'Mass air flow sensor',
  '2786': 'Throttle valve potentiometer 1',
  '2787': 'Throttle valve potentiometer 2',
  '2788': 'Vehicle speed',
  '2789': 'Rough running detection',
  '278A': 'Ambient temperature sensor',
  '278B': 'Engine coolant temperature sensor',
  '278C': 'Intake air temperature sensor',
  '278D': 'Radiator outlet temperature sensor',
  '278F': 'Alternator (under-excitation)',
  '2790': 'Radiator outlet temperature',
  '2791': 'Throttle adaptation required',
  '27A4': 'DME to EWS interface',
  '27A6': 'Fuel injector, cyl 1',
  '27A7': 'Fuel injector, cyl 5',
  '27A8': 'Fuel injector, cyl 3',
  '27A9': 'Fuel injector, cyl 6',
  '27AA': 'Fuel injector, cyl 2',
  '27AB': 'Fuel injector, cyl 4',
  '27B7': 'Fuel pump relay output stage',
  '27C2': 'A/C compressor control output stage',
  '27C3': 'Oil level sensor',
  '27C4': 'Main relay',
  '27CC': 'DMTL leakage',
  '27CD': 'DMTL module failure',
  '27DA': 'Alternator BSD fault',
  '27DB': 'Accelerator and brake pedal (signal)',
  '27DD': 'Engine coolant temp sensor (gradient)',
  '27DE': 'Engine coolant temp sensor (signal)',
  '27E2': 'Knock sensor 1',
  '27E3': 'Knock sensor 2',
  '27EB': 'CAN message, EGS',
  '27ED': 'CAN message, ASC/DSC',
  '27EE': 'CAN message, instrument cluster',
  '27F2': 'Tank fill level',
  '2812': 'Oil temperature',
  '281C': 'BSD interface signal',
  '283A': 'Oil condition sensor',
  '2892': 'Misfiring',
  '2895': 'Crankshaft sensor (signal)',
  '2896': 'Inlet camshaft sensor (signal)',
  '2897': 'Exhaust camshaft sensor (signal)',
  '28C1': 'O2 sensor pre-cat, bank 1',
  '28C2': 'O2 sensor pre-cat, bank 2',
  '2E95': 'Generator (alternator)',
  '2E97': 'Generator (alternator)',
  '2F17': 'Engine oil temperature too high',
  '2F44': 'EWS intervention',
  '2F4E': 'Road speed signal',
  '2F62': 'Brake light switch',
  '2F67': 'Clutch switch',
};
