// GENERATED FILE - do not edit by hand. Regenerate: node scripts/build-faultdb.mjs
// Source of truth: BMW SGBD FORTTEXTE tables (data/faults/**). Injected lazily via
// loadFaultDb() in faults.js so this literal isn't parsed before first paint.
// BMW_FAULT_DB: hex DTC -> English. BMW_FAULT_PHRASES: German fault text -> English.
window.BMW_FAULT_DB = {
  // 00xx
  "0000": "Fault location not defined",
  // 01xx
  "0100": "Air Flow Sensor HFM",
  "0105": "Atmospheric Pressure Sensor",
  "0110": "Intake Air Temperature Sensor",
  "0115": "Coolant Temperature Sensor",
  "0120": "Pedal Position Sensor 1",
  "0190": "Rail Pressure Sensor",
  // 02xx
  "0200": "Injector Cylinder 1",
  "0201": "Injector Cylinder 5",
  "0202": "Central locking: fuse",
  "0203": "Injector Cylinder 6",
  "0204": "Injector Cylinder 2",
  "0205": "Injector Cylinder 4",
  "0220": "Pedal Position Sensor 2",
  "0235": "Boost Pressure Sensor",
  // 03xx
  "0335": "Crankshaft RPM",
  "03E6": "EGR Regulation",
  // 04xx
  "0400": "EGR",
  "0404": "EGR 2",
  "0480": "Electric ECU Fan",
  // 05xx
  "0500": "Vehicle Speed Sensor Signal",
  "0560": "Internal Reference Voltage",
  // 06xx
  "0600": "DDE Error CAN Controller",
  "0605": "DDE Error",
  // 08xx
  "0801": "Window lift: fuse",
  // 11xx
  "1190": "Rail Pressure Regulation",
  "1195": "Rail Pressure Sensor",
  // 12xx
  "1250": "Delivery Pump Relay",
  "1255": "Delivery Pump Pressure Sensor",
  "1260": "Delivery Pump Control System",
  // 14xx
  "1430": "Boost Pressure or Actuator",
  "1470": "Boost Pressure Regulation",
  // 16xx
  "1612": "DME Incorrectly Coded",
  "1613": "MAP Control",
  "1640": "DDE Error EEPROM or Coding",
  // 1Axx
  "1A04": "Aux. Heater",
  // 1Dxx
  "1DF0": "Engine Stall",
  "1DF5": "EWS - Timeout",
  // 1Exx
  "1E00": "CAN Communication to ASC",
  "1E05": "Vehicle Speed Sensor",
  "1E25": "RPM Regulation",
  "1E30": "Boost Pressure Regulation or Actuator",
  "1E31": "Boost Pressure Regulation",
  "1E35": "Error During Switch off",
  "1E40": "A/D Converter",
  "1E45": "Capacitor Voltage 1 for Cyl 1, 2, 3",
  "1E50": "Capacitor Voltage 2 for Cyl 4, 5, 6",
  "1E55": "RPM Control",
  "1E60": "Power supply Pedal Sensor 1",
  // 27xx
  "2711": "Leak diagnostic pump output stage",
  "2712": "DMTL solenoid valve: control",
  "2713": "O2 sensors swapped",
  "2714": "O2 sensor heater post-cat (bank 2)",
  "2715": "O2 sensor heater, pre-cat, bank 2: control",
  "2716": "O2 sensor heater, post-cat, bank 1: control",
  "2717": "O2 sensor heater, post-cat, bank 2: control",
  "2718": "Crankshaft sensor: reference mark",
  "2719": "Crankshaft sensor: period",
  "271A": "O2 sensor, pre-cat, bank 1: signal",
  "271C": "O2 sensor, post-cat, bank 1: signal",
  "271D": "O2 sensor heater, pre-cat, bank 1: control",
  "271E": "O2 sensor heater post-cat",
  "271F": "O2 sensor aging, bank 1: period",
  "2720": "O2 sensor aging, bank 1: switching time",
  "2721": "O2 sensor aging, post-cat, bank 1",
  "2722": "O2 sensor, pre-cat, bank 2: signal",
  "2724": "O2 sensor, post-cat, bank 2: signal",
  "2725": "O2 sensor aging, bank 2: period",
  "2726": "O2 sensor aging, bank 2: switching time",
  "2727": "O2 sensor aging, post-cat, bank 2",
  "2728": "Lambda control adaptation multiplicative range 2",
  "2729": "Lambda control adaptation multiplicative range 2 (bank 2)",
  "272A": "Lambda control adaptation multiplicative range 1",
  "272B": "Lambda control adaptation multiplicative range 1 (bank 2)",
  "272C": "Lambda control adaptation additive per time",
  "272D": "Lambda control adaptation additive per time (bank 2)",
  "272E": "Lambda control adaptation additive per ignition",
  "272F": "Lambda control adaptation additive per ignition bank 2",
  "2730": "Idle speed control faulty",
  "2731": "Camshaft control intake",
  "2732": "Camshaft control intake B2 (8cyl)/exhaust (4cyl)",
  "2733": "Camshaft-crankshaft sync error",
  "2734": "Throttle potentiometer 1: signal implausible vs. MAF",
  "2735": "Throttle potentiometer 2: signal implausible vs. MAF",
  "2736": "Throttle valve controller PWM short test",
  "2737": "EWS 3.3 anti-tamper protection",
  "2738": "Catalyst conversion, bank 1",
  "2739": "Catalytic converter conversion LSU",
  "273A": "Catalytic converter conversion LSU bank 2",
  "273B": "Catalyst conversion, bank 1, via NOx sensor",
  "273C": "Catalyst conversion, bank 2, via NOx sensor",
  "273D": "Catalyst conversion, bank 2",
  "273E": "Exhaust temperature sensor 1 signal",
  "273F": "Exhaust temperature sensor 2 signal",
  "2740": "Accelerator pedal sensor 1: voltage supply",
  "2741": "Accelerator pedal sensor 2: voltage supply",
  "2742": "Misfire, cylinder 1",
  "2743": "Misfire, cylinder 5",
  "2744": "Misfire, cylinder 3",
  "2745": "Misfire, cylinder 6",
  "2746": "Misfire, cylinder 2",
  "2747": "Misfire, cylinder 4",
  "2748": "Misfire detection cyl. 7 in firing order",
  "2749": "Misfire detection cyl. 8 in firing order",
  "274A": "Misfire detection cyl. 9 in firing order",
  "274B": "Misfire detection cyl. 10 in firing order",
  "274C": "Misfire detection cyl. 11 in firing order",
  "274D": "Misfire detection cyl. 12 in firing order",
  "274E": "Misfire, multiple cylinders",
  "274F": "Misfire, sum fault, service-relevant",
  "2750": "Throttle position controller: briefly sticking",
  "2751": "Throttle position controller: permanently stuck",
  "2752": "Throttle position controller: stiff/sluggish",
  "2753": "Ignition coil, cylinder 1",
  "2754": "Ignition coil, cylinder 5",
  "2755": "Ignition coil, cylinder 3",
  "2756": "Ignition coil, cylinder 6",
  "2757": "Ignition coil, cylinder 2",
  "2758": "Ignition coil, cylinder 4",
  "2759": "Igniter 7 monitoring in firing order",
  "275A": "Igniter 8 monitoring in firing order",
  "275B": "Igniter 9 monitoring in firing order",
  "275C": "Igniter 10 monitoring in firing order",
  "275D": "Igniter 11 monitoring in firing order",
  "275E": "Igniter 12 monitoring in firing order",
  "275F": "Accelerator pedal sensor defective",
  "2760": "Secondary air system",
  "2761": "Secondary air system",
  "2762": "Secondary air valve",
  "2763": "Secondary air valve bank 2",
  "2764": "Secondary air pump relay: control",
  "2765": "Secondary air solenoid valve: control",
  "2766": "Camshaft sensor, intake: signal duration",
  "2767": "Camshaft sensor, exhaust: signal duration",
  "2768": "Camshaft sensor, intake: phase position",
  "2769": "Spring test throttle actuator opening spring",
  "276A": "Control unit selection",
  "276B": "Secondary air valve output stage bank 2",
  "276C": "Camshaft sensor, exhaust: phase position",
  "276D": "Fuel tank ventilation: function check",
  "276E": "Fuel tank purge functional check bank 2",
  "276F": "Secondary air mass sensor faulty",
  "2770": "Secondary air mass flow sensor",
  "2771": "Secondary air system blocked",
  "2772": "Purge valve: control",
  "2773": "Fuel tank purge valve output stage bank 2",
  "2774": "Engine-off time",
  "2775": "Engine torque monitoring level 2",
  "2776": "Multi-function steering wheel (MFL) interface",
  "2777": "DME self-test: A/D converter",
  "2778": "Clutch switch",
  "2779": "DME self-test: RAM",
  "277A": "Brake switch",
  "277B": "Control unit self-test ROM",
  "277C": "Control unit self-test RESET",
  "277D": "Battery voltage",
  "277E": "Torque limitation level 1",
  "277F": "Crankshaft sensor",
  "2780": "Reference mark sensor",
  "2781": "Camshaft sensor intake",
  "2782": "Camshaft sensor exhaust",
  "2783": "Hot-film mass air flow sensor (MAF)",
  "2785": "Throttle potentiometer",
  "2786": "Throttle potentiometer 1",
  "2787": "Throttle potentiometer 2",
  "2788": "Vehicle speed",
  "2789": "Rough road detection",
  "278A": "Ambient temperature",
  "278B": "Engine coolant temperature sensor",
  "278C": "Intake air temperature sensor",
  "278D": "Radiator outlet temperature sensor",
  "278E": "Intake manifold differential pressure sensor",
  "278F": "Alternator: under-excitation",
  "2790": "Radiator outlet temperature: implausible",
  "2791": "Swap detection without adaptation",
  "2792": "Throttle position monitoring",
  "2793": "Throttle actuator control range",
  "2794": "Throttle actuator",
  "2795": "Spring test throttle actuator closing spring",
  "2796": "Throttle valve: adaptation values faulty",
  "2797": "Throttle actuator fault during amplifier calibration",
  "2798": "Limp-home air point test",
  "2799": "Throttle adaptation abort due to ambient conditions",
  "279A": "Abort during UMA relearn",
  "279B": "Map-controlled thermostat: mechanical",
  "279C": "Map-controlled thermostat: control",
  "279D": "Engine fan: control",
  "279E": "Exhaust flap: control",
  "279F": "Fan A output stage",
  "27A0": "E-box fan: control",
  "27A1": "Throttle valve: startup check",
  "27A2": "Engine temperature sensor for lambda control",
  "27A3": "CAN timeout HDEV2 control unit",
  "27A4": "EWS 3.3 - DME interface",
  "27A5": "Throttle valve: re-adaptation",
  "27A6": "Injector, cylinder 1",
  "27A7": "Injector, cylinder 5",
  "27A8": "Injector, cylinder 3",
  "27A9": "Injector, cylinder 6",
  "27AA": "Injector, cylinder 2",
  "27AB": "Injector, cylinder 4",
  "27AC": "Injector 7 in firing order",
  "27AD": "Injector 8 in firing order",
  "27AE": "Injector 9 in firing order",
  "27AF": "Injector 10 in firing order",
  "27B0": "Injector 11 in firing order",
  "27B1": "Injector 12 in firing order",
  "27B2": "Brake light switch: signal",
  "27B3": "Diagnosis throttle/MAF calibration",
  "27B4": "Ambient pressure sensor",
  "27B5": "Camshaft control (VANOS), intake, bank 1: control",
  "27B6": "Intake VANOS output stage bank 2",
  "27B7": "Fuel pump relay: control",
  "27B8": "Differential pressure sensor plausibility",
  "27B9": "O2 sensor, pre-cat, bank 1: voltage swing",
  "27BA": "O2 sensor, pre-cat, bank 2: voltage swing",
  "27BB": "Camshaft control exhaust VANOS",
  "27BC": "Camshaft control exhaust VANOS bank 2",
  "27BD": "Camshaft control (VANOS), exhaust, bank 1: control",
  "27BE": "Exhaust VANOS output stage bank 2",
  "27BF": "Camshaft sensor intake bank 2",
  "27C0": "Camshaft sensor exhaust bank 2",
  "27C1": "Master camshaft sensor",
  "27C2": "A/C compressor control: activation",
  "27C3": "Thermal oil level sensor",
  "27C4": "Main relay",
  "27C5": "Brake light test switch: signal",
  "27C6": "LDP diagnosis fine leak",
  "27C7": "Main relay: switch-off delay",
  "27C8": "LDP system",
  "27C9": "LDP module",
  "27CA": "DMTL pump motor: control",
  "27CB": "DM-TL very fine leak (0.5mm) MIL off",
  "27CC": "DMTL: leak detected",
  "27CD": "DMTL: module fault",
  "27CE": "Load sensor monitoring",
  "27CF": "Ignition, cylinder 1",
  "27D0": "Ignition, cylinder 5",
  "27D1": "Ignition, cylinder 3",
  "27D2": "Ignition, cylinder 6",
  "27D3": "Ignition, cylinder 2",
  "27D4": "Ignition, cylinder 4",
  "27D5": "Idle speed control faulty",
  "27D6": "Idle actuator: control - position closed",
  "27D7": "Idle actuator: control - position open",
  "27D8": "Vacuum pump fault",
  "27D9": "DMTL heater: control",
  "27DA": "BSD alternator",
  "27DB": "Accelerator and brake pedal: signal implausible",
  "27DC": "EWS 3.3 rolling-code storage",
  "27DD": "Engine coolant temp sensor: gradient",
  "27DE": "Engine coolant temp sensor: signal",
  "27DF": "Engine coolant temp sensor: signal stuck",
  "27E0": "Crankshaft sensor: segment time measurement",
  "27E1": "Accelerator pedal sensor monitoring",
  "27E2": "Knock sensor 1",
  "27E3": "Knock sensor 2",
  "27E4": "Knock sensor 3",
  "27E5": "Knock sensor 4",
  "27E6": "Knock control zero test",
  "27E7": "Knock control offset",
  "27E8": "Knock control test pulse",
  "27E9": "Knock control zero test bank 2",
  "27EA": "CAN timeout HDEV",
  "27EB": "Message (EGS 2) from transmission (EGS) missing",
  "27EC": "Message (EGS 1) from transmission (EGS) missing",
  "27ED": "CAN timeout ASC/DSC",
  "27EE": "CAN timeout instrument cluster",
  "27EF": "CAN timeout ACC",
  "27F0": "MSR intervention plausibility",
  "27F1": "ACC intervention plausibility",
  "27F2": "Fuel level: plausibility",
  "27F3": "CAN timeout VVT control unit",
  "27F4": "CAN timeout VVT control unit bank 2",
  "27F5": "CAN timeout DME control unit",
  "27F6": "Accelerator pedal sensor",
  "27F7": "Accelerator pedal potentiometer 1",
  "27F8": "Accelerator pedal potentiometer 2",
  "27F9": "Automatic start: control",
  "27FA": "Auto-start input",
  "27FB": "Controlled air guidance: control",
  "27FD": "Auto-start",
  "27FE": "Knock control offset bank 2",
  "27FF": "Knock control test pulse bank 2",
  // 28xx
  "2800": "Message (I-cluster 2) from instrument cluster missing",
  "2801": "Idle speed implausible (air leak)",
  "2804": "Cruise control: request",
  "2805": "Cruise control switch: signal",
  "2806": "Cruise control: data transfer time limit reached",
  "2807": "Accelerator pedal potentiometer: signal",
  "2808": "Accelerator pedal sensor: signal",
  "2809": "Message (I-cluster 3) from instrument cluster missing",
  "280A": "Camshaft to crankshaft assignment",
  "280B": "Message (ASC 1) from ASC module missing",
  "280C": "Message (ASC 3) from ASC module missing",
  "280D": "Message (LWS) from steering angle sensor missing",
  "280E": "Message (SMG 1) from SMG module missing",
  "280F": "Message (ASC 4) from ASC module missing",
  "2810": "Engine speed monitoring",
  "2811": "Local-CAN communication fault",
  "2812": "Oil temperature",
  "2813": "Control unit monitoring group A",
  "2814": "DME Monitoring Group B",
  "2815": "DME Monitoring Group C",
  "2816": "DME Monitoring Speed Sensor or ECU Fault",
  "281A": "Message (TxU) missing",
  "281B": "Message (EKP) from electric fuel pump missing",
  "281C": "Bit-serial data interface (BSD): signal",
  "281D": "BSD alternator: signal",
  "281E": "Variable intake manifold (DISA): control",
  "281F": "DISA position feedback",
  "2820": "DISA plausibility",
  "2823": "O2 sensor heater pre-cat",
  "2824": "O2 sensor heater pre-cat bank 2",
  "2825": "Lambda Sensor Timing Bank 1",
  "2826": "Lambda Sensor Timing Bank 2",
  "2828": "CAN timeout ARS",
  "2829": "CAN timeout CAS",
  "282A": "CAN timeout IHKA",
  "282B": "CAN timeout PWML",
  "282C": "CAN timeout SZL",
  "282E": "Accelerator pedal sensor movement",
  "282F": "PT-CAN communication fault",
  "2830": "DME self-test: checksum",
  "2831": "DME self-test: processor monitoring",
  "2832": "ASR torque plausibility",
  "2833": "CAS plausibility",
  "2834": "IHKA plausibility",
  "2835": "PWML plausibility",
  "2836": "SZL plausibility",
  "2837": "EMF plausibility",
  "2838": "AAV output stage",
  "2839": "AAV functionality",
  "283A": "Oil condition sensor",
  "283B": "Camshaft control output stage bank 2",
  "283C": "Camshaft control output stage",
  "283D": "Powertrain CAN bus off",
  "283E": "Variable Valve Gear Output Stage Enable Line",
  "283F": "Oil pressure switch: signal implausible",
  "2841": "Air-shrouded injectors output stage",
  "2850": "VVT guide sensor",
  "2851": "VVT guide sensor (bank 2)",
  "2852": "VVT reference sensor",
  "2853": "VVT reference sensor (bank 2)",
  "2854": "VVT sensor plausibility",
  "2855": "VVT sensor plausibility (bank 2)",
  "2856": "VVT sensor supply voltage",
  "2857": "VVT sensor supply voltage (bank 2)",
  "2858": "VVT learning function stop",
  "2859": "VVT learning function stop (bank 2)",
  "285A": "VVT actuator monitoring",
  "285B": "VVT actuator monitoring (bank 2)",
  "285C": "VVT CAN communication",
  "285D": "VVT CAN communication (bank 2)",
  "285E": "VVT control unit internal fault",
  "285F": "VVT control unit internal fault (bank 2)",
  "2860": "VVT output stage",
  "2861": "VVT output stage (bank 2)",
  "2862": "VVT power supply",
  "2863": "VVT power supply (bank 2)",
  "2865": "Power limitation VVT limp-home",
  "2866": "VVT stops learning required",
  "2867": "Variable Valve Gear Overload",
  "2869": "DME self-test: RAM check faulty",
  "286A": "DME self-test: knock sensor module",
  "286B": "DME self-test: multiple output-stage module",
  "286F": "EGR valve output stage",
  "2870": "EGR valve monitoring",
  "2871": "EGR valve position sensor",
  "2872": "EGR valve diagnosis",
  "2873": "HDEV control unit 1 output stage bank 1",
  "2874": "HDEV control unit 1 output stage bank 2",
  "2875": "HDEV control unit 1 output stage bank 3",
  "2876": "HDEV control unit 2 output stage bank 1",
  "2877": "HDEV control unit 2 output stage bank 2",
  "2878": "HDEV control unit 2 output stage bank 3",
  "2879": "Exhaust temperature sensor 4 signal",
  "287A": "Pressure control valve output stage",
  "287B": "Exhaust temperature sensor 3 signal",
  "287C": "Intake manifold pressure sensor",
  "287D": "Rail pressure sensor signal",
  "287E": "Pressure control valve",
  "287F": "High-pressure sensor test",
  "2880": "EGR system",
  "2881": "Swirl generation actuator output stage",
  "2882": "Mixture preparation, bank 1",
  "2883": "Mixture preparation, bank 2",
  "2892": "Misfire at low fuel level",
  "2893": "Control unit internal temperature",
  "2894": "Irreversible control unit fault",
  "2895": "Crankshaft sensor: signal",
  "2896": "Camshaft sensor: intake signal",
  "2897": "Camshaft sensor: exhaust signal",
  "2898": "O2 sensor, post-cat, bank 1: signal",
  "2899": "O2 sensor, post-cat, bank 2: signal",
  "289A": "O2 sensor heater, pre-cat, bank 1: function",
  "289B": "O2 sensor heater, pre-cat, bank 2: function",
  "289C": "O2 sensor heater, post-cat, bank 1: function",
  "289D": "O2 sensor heater, post-cat, bank 2: function",
  "289E": "O2 sensor, pre-cat, bank 1",
  "289F": "O2 sensor, pre-cat, bank 2",
  "28A0": "Fuel circuit changeover output stage",
  "28A1": "Cruise control",
  "28A2": "Air path",
  "28A4": "Engine speed",
  "28A5": "Accelerator pedal sensor",
  "28A7": "Message monitoring: NOx sensor 1",
  "28A8": "Message monitoring: NOx sensor 2",
  "28AA": "Idle controller",
  "28AB": "External torque request: monitoring",
  "28AC": "Target torque",
  "28AD": "Actual torque",
  "28AE": "Torque limitation",
  "28B1": "Engine speed limitation",
  "28B2": "Engine speed limitation: reset",
  "28B3": "Throttle valve: continuous adaptation",
  "28B4": "Driving dynamics control (DTC) button",
  "28B5": "Sound flap: signal",
  "28B6": "Intake camshaft, bank 1: mechanical",
  "28B8": "Exhaust camshaft, bank 1: mechanical",
  "28BA": "Intake camshaft, bank 1: stiff/sluggish",
  "28BC": "Exhaust camshaft, bank 1: stiff/sluggish",
  "28BD": "Intake camshaft sensor: locking",
  "28BE": "Exhaust camshaft sensor: locking",
  "28BF": "NOx sensor 1",
  "28C0": "NOx sensor 2",
  "28C1": "O2 sensor, pre-cat, bank 1",
  "28C2": "O2 sensor, pre-cat, bank 2",
  "28C3": "O2 sensor heater, pre-cat, bank 1: function",
  "28C4": "O2 sensor heater, pre-cat, bank 2: function",
  "28C5": "O2 sensor, post-cat, bank 1: system check",
  "28C6": "O2 sensor, post-cat, bank 2: system check",
  "28C8": "Lambda control deviation",
  "28C9": "Lambda control deviation bank 2",
  "28CA": "Ozone conversion: too low",
  "28CB": "Ozone sensor 2",
  "28CC": "Ozone sensor 1",
  "28CF": "Fuel pump: emergency shutoff",
  "28D0": "Fuel pump",
  "28D2": "Boost pressure sensor",
  "28D3": "Plausibility ambient to boost pressure",
  "28D4": "Boost pressure control valve output stage",
  "28D5": "Turbo recirculation valve output stage",
  "28D6": "Process Error- Coding",
  "28D7": "Alternator Communication",
  "28D8": "RAM Backup",
  "28DB": "Variable Valve Gear Minimum Lift Adaptation Exceeded",
  "28DD": "Air mass system",
  "28E6": "O2 sensor evaluation module, bank 1: self-diagnosis",
  "28E7": "O2 sensor evaluation module, bank 2: self-diagnosis",
  "28E8": "O2 sensors, bank 1: trim control",
  "28E9": "O2 sensors, bank 2: trim control",
  "28EA": "O2 sensor, post-cat, bank 1: signal",
  "28EB": "O2 sensor, post-cat, bank 2: signal",
  "28EC": "O2 sensor, post-cat, bank 1: signal at full load",
  "28ED": "O2 sensor, post-cat, bank 2: signal at full load",
  "28F0": "O2 sensor, post-cat, bank 1: system check",
  "28F1": "O2 sensor, post-cat, bank 2: system check",
  "28F2": "O2 sensors, bank 1: trim control",
  "28F3": "O2 sensors, bank 2: trim control",
  "28F4": "O2 sensor, pre-cat, bank 1: cold test",
  "28F5": "O2 sensor, pre-cat, bank 2: cold test",
  "28F6": "O2 sensor, post-cat, bank 1: cold test",
  "28F7": "O2 sensor, post-cat, bank 2: cold test",
  "28F9": "Running roughness: segment time measurement",
  "28FA": "Torque during shift phase",
  "28FB": "Active Cruise Control (ACC)",
  "28FF": "DME self-test",
  // 29xx
  "2900": "DME self-test",
  "293C": "Message monitoring: torque request AFS",
  "293D": "Message monitoring: EKP (fuel pump)",
  "2947": "Message monitoring: torque request ACC",
  "2948": "Message monitoring: ARS",
  "2949": "Message monitoring: CAS",
  "294A": "Message monitoring: torque request SMG",
  "294B": "Message monitoring: speed DSC",
  "294C": "Message monitoring: status DSC",
  "294D": "Message monitoring: torque request EGS",
  "294E": "Message monitoring: transmission data EGS/SMG",
  "294F": "Message monitoring: torque request SMG",
  "2950": "Message monitoring: A/C",
  "2951": "Message monitoring: temperature, instrument cluster",
  "2952": "Message monitoring: odometer, instrument cluster",
  "2953": "Message monitoring: status, instrument cluster",
  "2954": "Message monitoring: battery voltage, power module",
  "2955": "Message monitoring: charging voltage, power module",
  "2956": "Message monitoring: cruise control operation, column switch",
  "2957": "Message monitoring: steering angle, column switch center",
  "2958": "Message monitoring: sport button",
  "2960": "O2 sensor, pre-cat, bank 1",
  "2961": "O2 sensor, pre-cat, bank 2",
  "2962": "O2 sensor, pre-cat, bank 1: dynamics",
  "2963": "O2 sensor, pre-cat, bank 2: dynamics",
  "2964": "O2 sensor, pre-cat, bank 1: ceramic temperature",
  "2965": "O2 sensor, pre-cat, bank 2: ceramic temperature",
  "2966": "O2 sensor, pre-cat, bank 1: signal",
  "2967": "O2 sensor, pre-cat, bank 2: signal",
  "296A": "O2 sensors, pre-cat: swapped",
  "296B": "O2 sensors, post-cat: swapped",
  "2972": "Jet Pump for Brake Servo",
  "2973": "O2 sensor, pre-cat, bank 1: wiring",
  "2974": "O2 sensor, pre-cat, bank 2: wiring",
  "2986": "O2 sensor, pre-cat, bank 1: system check",
  "2987": "O2 sensor, pre-cat, bank 2: system check",
  "2988": "O2 sensor, pre-cat, bank 1: system check",
  "2989": "O2 sensor, pre-cat, bank 2: system check",
  "2990": "NOx sensor 1: system test",
  "2991": "NOx sensor 2: system test",
  "2992": "NOx sensor 1: system test dynamics",
  "2993": "NOx sensor 2: system test dynamics",
  "2994": "NOx sensor 1: heater power",
  "2995": "NOx sensor 2: heater power",
  "2996": "NOx sensor 1: system test plausibility",
  "2997": "NOx sensor 2: OBD-II diagnosis plausibility",
  "2998": "NOx sensor 1: system test",
  "2999": "NOx sensor 2: system test",
  "299A": "Fault management EGS",
  "299B": "Battery sensor: signal",
  "299C": "Battery sensor: function",
  "299D": "Battery sensor: signal transmission",
  "299E": "O2 sensor, post-cat, bank 1: signal",
  "299F": "O2 sensor, post-cat, bank 1: signal",
  "29A0": "O2 sensor, post-cat, bank 2: signal",
  "29A1": "O2 sensor, post-cat, bank 2: signal",
  "29A2": "O2 sensor, pre-cat, bank 2: signal",
  "29A3": "O2 sensor, pre-cat, bank 2: signal",
  "29A4": "O2 sensor heater, pre-cat, bank 1: control",
  "29A5": "O2 sensor heater, pre-cat, bank 2: control",
  "29A6": "O2 sensor, pre-cat, bank 1: signal",
  "29A7": "O2 sensor, pre-cat, bank 1: signal",
  "29A8": "Message monitoring: network fault, power management",
  "29A9": "Message monitoring: battery, power management",
  "29AB": "Torque request via CAN",
  "29AE": "Fuel filler cap",
  "29AF": "Message and signal monitoring, terminal 15",
  "29B5": "Secondary air system",
  "29B6": "Cylinder shutoff",
  "29CC": "Misfire Several Cylinders",
  "29CD": "Misfire Cyl 1",
  "29CE": "Misfire Cyl 2",
  "29CF": "Misfire Cyl 3",
  "29D0": "Misfire Cyl 4",
  "29DD": "Rough Running Detection",
  "29E5": "Mixture Adaptation 1 Air Density Upper Speed Range",
  "29E6": "Mixture Adaptation 2 Air Density Upper Speed Range",
  "29E7": "Mixture Adaptation 1 Air Leak",
  "29E8": "Mixture Adaptation 2 Air Leak",
  "29ED": "Mixture Adaptation 1 Air Density Lower Speed Range",
  "29EE": "Mixture Adaptation 2 Air Density Lower Speed Range",
  "29F4": "Catalytic Converter Efficiency 1",
  "29FE": "Aux Air System",
  "29FF": "Aux Air System",
  // 2Axx
  "2A03": "Aux Air Pump Relay",
  "2A19": "Tank Venting Valve",
  "2A59": "Valvetronic Eccentric Shaft Sensor 1",
  "2A5B": "Valvetronic Eccentric Shaft Sensor 1",
  "2A5D": "Valvetronic Eccentric Shaft Sensor 1",
  "2A5F": "Valvetronic Eccentric Shaft Sensor 1",
  "2A61": "Valvetronic Adaptation 1",
  "2A63": "Valvetronic Servomotor 1",
  "2A67": "Valvetronic Internal Fault",
  "2A69": "Valvetronic Voltage Supply Servomotor 1",
  "2A6B": "Valvetronic Power Limitation Servomotor",
  "2A6C": "Valvetronic Adaptation",
  "2A6D": "Valvetronic Electrical Overload Protection 1",
  "2A6F": "Valvetronic Minimum Lift Exceeded",
  "2A70": "Valvetronic Servomotor",
  "2A71": "Valvetronic Relief Relay",
  "2A80": "Inlet VANOS Activation 1",
  "2A83": "Inlet VANOS 1",
  "2A85": "Exhaust VANOS Activation 1",
  "2A88": "Exhaust VANOS 1",
  "2AD8": "EAC sensor: monitoring",
  "2AD9": "EAC sensor: coding",
  "2ADA": "EAC sensor: electrical fault",
  "2ADC": "EAC sensor: communication",
  // 2Bxx
  "2B5C": "Crankshaft Sensor",
  "2B5D": "Crankshaft Sensor",
  "2B62": "Camshaft Sensor 1 Inlet",
  "2B63": "Camshaft Sensor 2 Exhaust",
  "2B66": "Camshaft Sensor",
  "2B70": "Variable Intake System",
  "2B7F": "Idle Speed Control",
  "2B80": "Idle Speed Control",
  "2B8A": "Control Module- Internal Fault Knock Control",
  "2B8B": "Control Module- Internal Fault Knock Control",
  "2B8C": "Control Module- Internal Fault Knock Control",
  "2B98": "Control Module- Internal Fault RAM",
  "2B99": "Control Module- Internal Fault RAM",
  "2B9A": "Control Module- Internal Fault RAM",
  "2B9B": "Control Module- Internal Fault ROM",
  "2B9C": "Control Module- Internal Fault Reset",
  "2BA7": "Engine Torque too High",
  // 2Cxx
  "2C24": "O2 sensors pre-cat Swapped",
  "2C45": "O2 sensor pre-cat 1",
  "2C46": "O2 sensor pre-cat 2",
  "2C6A": "O2 sensor post-cat Swapped",
  "2C6D": "O2 sensor post-cat 1 Timing",
  "2C6E": "O2 sensor post-cat 2 Timing",
  "2C6F": "O2 sensor post-cat 1",
  "2C70": "O2 sensor post-cat 2",
  "2C71": "O2 sensor post-cat 1",
  "2C72": "O2 sensor post-cat 2",
  "2C9C": "O2 sensor Heater pre-cat 1",
  "2C9D": "O2 sensor Heater pre-cat 2",
  "2CA0": "O2 sensor Heater pre-cat 1",
  "2CA1": "O2 sensor Heater pre-cat 2",
  "2CA2": "O2 sensor Heater pre-cat 1",
  "2CA3": "O2 sensor Heater pre-cat 2",
  "2CA8": "O2 sensor Heater post-cat 1",
  "2CA9": "O2 sensor Heater post-cat 2",
  "2CEF": "Throttle Valve Actuator",
  "2CF0": "Throttle Valve Actuator",
  "2CF1": "Throttle Valve Actuator",
  "2CF8": "Throttle Valve Potentiometer",
  "2CF9": "Throttle Valve Potentiometer 1",
  "2CFA": "Throttle Valve Potentiometer 2",
  "2CFF": "Throttle Valve Actuator",
  // 2Dxx
  "2D00": "Throttle Valve Actuator",
  "2D01": "Throttle Valve Actuator",
  "2D02": "Throttle Valve Actuator",
  "2D03": "Throttle Valve Actuator",
  "2D04": "Throttle Valve Actuator",
  "2D05": "Throttle Valve Actuator",
  "2D08": "Throttle Actuator",
  "2D0F": "Mass Air Flow Sensor Signal",
  "2D19": "Accelerator Pedal Module",
  "2D1A": "Accelerator Pedal Module",
  "2D1B": "Accelerator Pedal Module Signal 1",
  "2D1C": "Accelerator Pedal Module Signal 2",
  "2D28": "Intake Manifold Pressure Sensor Signal",
  "2D29": "Intake Manifold Pressure Sensor Plausibility",
  "2D6E": "Control Module Internal Fault Torque Monitoring",
  "2D6F": "Load Sensor Monitoring",
  "2D70": "Control Module Internal Fault",
  "2D71": "Control Module Internal Fault",
  "2D72": "Control Module Internal Fault",
  "2D73": "Fuel Pressure Sensor",
  "2D74": "Fuel Pressure Sensor",
  "2D75": "Crankshaft Sensor",
  "2D76": "Accelerator Pedal Module",
  "2DC6": "Fuel level value: plausibility",
  // 2Exx
  "2E24": "Ignition Coil Cyl 1",
  "2E25": "Ignition Coil Cyl 2",
  "2E26": "Ignition Coil Cyl 3",
  "2E27": "Ignition Coil Cyl 4",
  "2E30": "Fuel Injector Cyl 1",
  "2E31": "Fuel Injector Cyl 2",
  "2E32": "Fuel Injector Cyl 3",
  "2E33": "Fuel Injector Cyl 4",
  "2E68": "Knock Sensor Signal 1",
  "2E69": "Knock Sensor Signal 2",
  "2E95": "Generator (alternator)",
  "2E97": "Generator (alternator)",
  "2EE0": "Engine Coolant Temperature Sensor Signal",
  "2EEA": "Radiator Outlet Temperature Sensor Signal",
  "2EF4": "Map Thermostat Mechanism Jammed",
  "2EF5": "Map Thermostat Activation",
  "2EFE": "Electric fan",
  "2EFF": "Electric fan: self-diagnosis",
  // 2Fxx
  "2F08": "Intake Air Temperature Sensor Signal",
  "2F09": "Intake air temperature sensor: plausibility",
  "2F12": "A/C Compressor Relay",
  "2F17": "Engine oil temperature too high",
  "2F44": "EWS intervention",
  "2F45": "EWS Data Line",
  "2F46": "EWS Calibration",
  "2F4E": "Road speed signal",
  "2F4F": "Vehicle speed: plausibility",
  "2F62": "Brake light switch",
  "2F67": "Clutch switch",
  "2F76": "Control Module Internal Fault Ambient Pressure Sensor",
  "2F85": "Control module Internal fault Internal Temperature Sensor",
  "2F8A": "Power supply",
  "2F94": "Fuel Pump Relay Activation",
  "2F99": "Ambient temperature sensor: plausibility",
  "2F9A": "Ambient temperature sensor: communication",
  "2F9E": "Oil Level Sensor",
  "2FA3": "Coding Error",
  // 30xx
  "3000": "Brake Light or Brake Light Test Switch",
  "3005": "Voltage Supply KL15",
  // 35xx
  "3505": "Glow Plug System",
  "3506": "Glow Plug System 2",
  "3510": "DDE Main Relay",
  "3515": "A/C Power Output",
  "3520": "Engine Boost Actuation",
  "3565": "High Pressure Pump",
  "3580": "High Pressure Pump Shut Off Valve",
  "3596": "Brake Light Switch",
  // 36xx
  "3600": "Atmospheric Pressure Sensor",
  "3605": "Air Flow Meter HFM 1 or 2",
  "3610": "EGR System",
  "3615": "EGR System - Regulation",
  "3620": "Air Flow Meter HFM Signal",
  // 3Cxx
  "3C1D": "Crankshaft sensor: signal",
  "3C1E": "Camshaft sensor: intake signal",
  "3C1F": "Camshaft sensor: exhaust signal",
  // 3Dxx
  "3D33": "Torque request via CAN",
  // 3Exx
  "3E90": "Crankshaft sensor, signal",
  "3E91": "Crankshaft sensor, signal",
  "3E95": "Intake air Temperature Sensor",
  "3EA0": "Crankshaft Position Sensor",
  "3EA1": "Crankshaft Position Sensor",
  "3EA5": "Intake air Temperature Sensor",
  "3EA6": "Intake air Temperature Sensor",
  "3EB0": "Speed calculation",
  "3EB5": "Air flow Sensor 2",
  "3EB6": "Air flow Sensor 2",
  "3EC0": "Camshaft sensor, signal",
  "3EC1": "Camshaft sensor, signal",
  "3EC7": "Master/slave monitoring",
  "3ED0": "Camshaft Sensor - No Signal",
  "3ED1": "Camshaft Sensor - Wrong Signal",
  "3ED5": "Air Flow Sensor 2",
  "3ED6": "Air Flow Sensor 2",
  "3EDC": "Variant Coding",
  "3EDD": "Variant Coding",
  "3EE0": "(0117) Coolant temperature sensor, signal",
  "3EE1": "(0118) Coolant temperature sensor, signal",
  "3EE2": "Coolant temperature sensor, signal",
  "3EE3": "Coolant temperature sensor, signal",
  "3EE5": "Air Mass Flow Sensor 2",
  "3EE6": "Air Mass Flow Sensor 2",
  "3EE7": "Air Mass Flow Sensor 2",
  "3EED": "Power Management Closed Circuit Current",
  "3EF3": "(0115) Coolant temperature sensor, plausibility",
  "3EF5": "Intake Air Temperature Sensor 2 (HFM Reference Signal)",
  "3EF6": "Intake Air Temperature Sensor 2 (HFM Reference Signal)",
  "3EF7": "Intake Air Temperature Sensor 2 (HFM Reference Signal)",
  "3EFB": "Thermal Oil Level Sensor",
  "3EFC": "Thermal Oil Level Sensor",
  "3EFD": "Thermal Oil Level Sensor",
  // 3Fxx
  "3F00": "(0238) Boost pressure sensor, signal",
  "3F01": "(0237) Boost pressure sensor, signal",
  "3F02": "Boost pressure sensor, signal",
  "3F03": "(0236) Boost pressure sensor, signal",
  "3F05": "(0701) MIL OFF",
  "3F10": "Accelerator pedal module potentiometer 1, signal",
  "3F11": "Accelerator pedal module potentiometer 1, signal",
  "3F13": "Accelerator pedal module potentiometer 1, signal",
  "3F15": "(0700) MIL On",
  "3F20": "Accelerator pedal module potentiometer 2, signal",
  "3F21": "Accelerator pedal module potentiometer 2, signal",
  "3F23": "Accelerator pedal module potentiometer 2, signal",
  "3F25": "Charge air hose monitoring",
  "3F30": "(0193) Rail pressure sensor, signal",
  "3F31": "(0192) Rail pressure sensor, signal",
  "3F35": "Charge air hose monitoring at idle",
  "3F40": "(3000) Rail pressure sensor offset test",
  "3F41": "(3001) Rail pressure sensor offset test",
  "3F47": "Brake Light or Brake Light Test Switch",
  "3F48": "Redundant evaluation of brake light/brake test switch",
  "3F50": "(0503) Vehicle speed signal",
  "3F51": "Vehicle speed signal",
  "3F52": "Vehicle speed signal",
  "3F53": "(0501) Vehicle speed signal",
  "3F57": "(1272) Boost pressure actuator",
  "3F60": "Pedal Position Sensor Ref. VSS",
  "3F62": "(0500) Vehicle speed signal via CAN",
  "3F67": "Filling Pressure Modulator 2",
  "3F70": "Intake air temperature sensor, signal",
  "3F71": "Intake air temperature sensor, signal",
  "3F72": "Intake air temperature sensor, signal",
  "3F77": "(1273) Boost pressure actuator, control",
  "3F80": "Ambient temperature sensor, signal",
  "3F81": "Ambient temperature sensor, signal",
  "3F82": "Ambient temperature sensor, signal",
  "3F87": "Boost Pressure Modulator 2",
  "3F90": "Oil pressure sensor, signal",
  "3F91": "Oil pressure sensor, signal",
  "3F97": "(1274) Boost pressure actuator, supply voltage",
  "3FA0": "Oil temperature sensor",
  "3FA1": "Oil temperature sensor",
  "3FA2": "Oil temperature sensor",
  "3FA3": "Oil temperature sensor",
  "3FB0": "Air Flow Meter - Signal too High or short circuit to B+",
  "3FB1": "Air Flow Meter - Signal too Low or Short circuit to B",
  "3FB5": "Control master/slave",
  "3FB6": "Control master/slave",
  "3FB7": "Control Unit - Internal Master",
  "3FC0": "(1261) Mass air flow sensor (MAF)",
  "3FD0": "(1262) Mass air flow sensor (MAF)",
  "3FE0": "(3261) Mass air flow sensor (MAF)",
  "3FE1": "(3262) Mass air flow sensor (MAF)",
  "3FF0": "(3263) Mass air flow sensor (MAF)",
  "3FF1": "(3264) Mass air flow sensor (MAF)",
  // 40xx
  "4000": "Fuel temperature sensor, signal",
  "4001": "Fuel temperature sensor, signal",
  "4010": "Exhaust back-pressure sensor pre-DPF, signal",
  "4011": "Exhaust back-pressure sensor pre-DPF, signal",
  "4020": "Exhaust gas temperature sensor pre-DPF, signal",
  "4021": "Exhaust gas temperature sensor pre-DPF, signal",
  "4030": "(0545) Exhaust gas temperature sensor pre-cat, signal",
  "4031": "(0546) Exhaust gas temperature sensor pre-cat, signal",
  "4032": "Exhaust gas temperature sensor pre-cat, signal",
  "4060": "(2229) Ambient pressure sensor (in control unit), signal",
  "4061": "(2228) Ambient pressure sensor (in control unit), signal",
  "4062": "Ambient pressure sensor (in control unit), signal",
  "4063": "(2227) Ambient pressure sensor (in control unit), signal",
  "4072": "Clutch switch, signal",
  "4073": "Clutch switch, signal",
  "4080": "Brake Light or Brake Light Test Switch",
  "4082": "Brake light/brake test switch, signals",
  "4083": "Brake light/brake test switch, signals",
  "4093": "Safety shutdown",
  "40A0": "Alternator load signal",
  "40A1": "Alternator load signal",
  "40B0": "Fault path 1 for air condition pressure (nv)",
  "40B1": "Fault path 1 for air condition pressure (nv)",
  "40B2": "Fault path 1 for air condition pressure (nv)",
  "40B3": "Fault path 1 for air condition pressure (nv)",
  "40C0": "Fault path 2 for air condition pressure (nv)",
  "40C1": "Fault path 2 for air condition pressure (nv)",
  "40D0": "Fault path for analog air condition pressure (nv)",
  "40D1": "Fault path for analog air condition pressure (nv)",
  "40E0": "Alternator",
  // 41xx
  "4100": "A/C Power Output",
  "4101": "A/C Power Output",
  "4102": "A/C Power Output",
  "4103": "A/C Power Output",
  "4108": "Control master/slave",
  "410C": "Swirl flap actuator",
  "4112": "Fault path of air condition power stage (nv)",
  "4113": "Fault path of air condition power stage (nv)",
  "4117": "Control master/slave",
  "4118": "Control master/slave",
  "4120": "DDE main relay",
  "4121": "DDE main relay",
  "4125": "Power supply",
  "4126": "Power supply",
  "4130": "(1425) Swirl flap actuator, control",
  "4135": "Power supply",
  "4136": "Power supply",
  "4140": "Swirl flap",
  "4141": "(1426) Swirl flap actuator, control",
  "4145": "Power supply",
  "4146": "Power supply",
  "4152": "(1427) Swirl flap actuator, control",
  "4153": "(1428) Swirl flap actuator, control",
  "4155": "Exhaust flap actuator, control",
  "4156": "Exhaust flap actuator, control",
  "4157": "Exhaust flap actuator, control",
  "4158": "Exhaust flap actuator, control",
  "4160": "Pre-feed pump relay, control",
  "4161": "Pre-feed pump relay, control",
  "4162": "Pre-feed pump relay, control",
  "4163": "Pre-feed pump relay, control",
  "4165": "Particulate filter system",
  "4166": "Particulate filter system",
  "4175": "Exhaust gas temperature sensor pre-DPF, signal",
  "4176": "Exhaust gas temperature sensor pre-DPF, signal",
  "4178": "Exhaust gas temperature sensor pre-DPF, signal",
  "4180": "(1251) Boost pressure actuator, control",
  "4185": "Exhaust gas temperature sensor pre-cat, signal",
  "4186": "Exhaust gas temperature sensor pre-cat, signal",
  "4188": "Exhaust gas temperature sensor pre-cat, signal",
  "4190": "Boost Pressure Actuator",
  "4191": "(1252) Boost pressure actuator, control",
  "419A": "Atmospheric Pressure Sensor DDE",
  "419B": "Atmospheric Pressure Sensor DDE",
  "41A0": "Boost Pressure Actuator",
  "41A1": "Boost Pressure Actuator - Adjustment",
  "41A2": "(1253) Boost pressure actuator, control",
  "41A3": "(1254) Boost pressure actuator, control",
  "41A6": "Message CBS Reset",
  "41A7": "Message CBS Reset",
  "41AA": "Boost Pressure Sensor",
  "41AB": "Boost Pressure Sensor",
  "41B0": "(1212) EGR actuator, control",
  "41B5": "Transmission Fluid Temperature Sensor",
  "41BA": "Exhaust Backpressure Sensor",
  "41BB": "Exhaust Backpressure Sensor",
  "41C0": "Exhaust air flap actuator, control",
  "41C1": "Exhaust air flap actuator, control",
  "41C2": "Exhaust air flap actuator, control",
  "41C3": "Exhaust air flap actuator, control",
  "41CD": "Exhaust Backpressure Sensor - Plausibility",
  "41D0": "EGR Regulation",
  "41D1": "(1213) EGR actuator, control",
  "41D5": "(2246) O2 sensor, Nernst voltage signal",
  "41D6": "(2245) O2 sensor, Nernst voltage signal",
  "41D7": "(2243) O2 sensor, Nernst voltage signal",
  "41D8": "O2 sensor, Nernst voltage signal",
  "41E0": "EGR Regulation",
  "41E2": "(1286) EGR actuator, control",
  "41E3": "(1269) EGR actuator, control",
  "41E5": "(2239) O2 sensor, pump current signal",
  "41E6": "(2238) O2 sensor, pump current signal",
  "41E7": "(2237) O2 sensor, pump current signal",
  "41E8": "O2 sensor, pump current signal",
  "41F0": "Electric fan, control",
  "41F1": "Electric fan, control",
  "41F2": "Electric fan, control",
  "41F3": "Electric fan, control",
  "41F5": "(2253) O2 sensor, virtual ground signal",
  "41F6": "(2252) O2 sensor, virtual ground signal",
  "41F7": "(2251) O2 sensor, virtual ground signal",
  "41F8": "O2 sensor, virtual ground signal",
  // 42xx
  "4203": "Glow control unit",
  "4205": "(0032) O2 sensor, heater control",
  "4206": "(0031) O2 sensor, heater control",
  "4207": "(0030) O2 sensor, heater control",
  "4208": "O2 sensor, heater control",
  "420B": "EGR in Regen Mode",
  "4211": "Glow plug cylinder 1, control",
  "4212": "Glow plug cylinder 1, control",
  "4213": "Glow plug cylinder 1, control",
  "4217": "O2 sensor",
  "4221": "Glow plug cylinder 2, control",
  "4222": "Glow plug cylinder 2, control",
  "4223": "Glow plug cylinder 2, control",
  "4225": "(0132) O2 sensor",
  "4226": "(0131) O2 sensor",
  "422A": "EGR in Regen Mode",
  "4231": "Glow plug cylinder 3, control",
  "4232": "Glow plug cylinder 3, control",
  "4233": "Glow plug cylinder 3, control",
  "4235": "Control unit internal 21",
  "4236": "Control unit internal 21",
  "4241": "Glow plug cylinder 4, control",
  "4242": "Glow plug cylinder 4, control",
  "4243": "Glow plug cylinder 4, control",
  "4245": "Control unit internal 22",
  "4246": "Control unit internal 22",
  "4251": "Glow plug cylinder 5, control",
  "4252": "Glow plug cylinder 5, control",
  "4253": "Glow plug cylinder 5, control",
  "4258": "Control unit internal 23",
  "425D": "Accelerator Pedal Potentiometer Plausibility",
  "4261": "Glow plug cylinder 6, control",
  "4262": "Glow plug cylinder 6, control",
  "4263": "Glow plug cylinder 6, control",
  "4267": "O2 sensor, shunt detection",
  "4271": "Glow plug cylinder 7, control",
  "4272": "Glow plug cylinder 7, control",
  "4273": "Glow plug cylinder 7, control",
  "4275": "O2 sensor, heater",
  "4276": "O2 sensor, heater",
  "4281": "Glow plug cylinder 8, control",
  "4282": "Glow plug cylinder 8, control",
  "4283": "Glow plug cylinder 8, control",
  "4287": "O2 sensor",
  "4288": "O2 sensor",
  "428B": "Boost Pressure Control of Large Turbo Control Deviation",
  "4293": "Control unit internal 16",
  "4296": "O2 sensor",
  "4298": "O2 sensor",
  "429A": "Boost Pressure Control of Large Turbo Control Deviation",
  "42A0": "Glow relay (nv)",
  "42A1": "Glow relay (nv)",
  "42A2": "Glow relay (nv)",
  "42A3": "Glow relay (nv)",
  "42B1": "Glow relay (nv)",
  "42B2": "Glow relay (nv)",
  "42B5": "Speed monitoring",
  "42C0": "Oil pressure warning light, control",
  "42C1": "Oil pressure warning light, control",
  "42C2": "Oil pressure warning light, control",
  "42C3": "Oil pressure warning light, control",
  "42D0": "Power Stage fault status for MIL (nv)",
  "42D1": "Power Stage fault status for MIL (nv)",
  "42D2": "Power Stage fault status for MIL (nv)",
  "42D3": "Power Stage fault status for MIL (nv)",
  "42D5": "Injector Cylinder 7",
  "42D6": "Injector Cylinder 7",
  "42D7": "Injector Cylinder 7",
  "42D8": "Injector Cylinder 7",
  "42E2": "Rail pressure control switchover PCV",
  "42F2": "Rail pressure control switchover MeUn",
  "42F5": "Injector Cylinder 8",
  "42F6": "Injector Cylinder 8",
  "42F7": "Injector Cylinder 8",
  "42F8": "Injector Cylinder 8",
  // 43xx
  "4302": "(0001) Quantity control valve, control",
  "4303": "(1291) Quantity control valve, control",
  "4310": "(0004) Quantity control valve, control",
  "4321": "Quantity control valve, control",
  "4332": "Rail pressure control valve, control",
  "4333": "Rail pressure control valve, control",
  "4340": "Rail pressure control valve, control",
  "4351": "(0091) Rail pressure control valve, control",
  "4360": "Current control for rail pressure control valve",
  "4361": "Current control for rail pressure control valve",
  "4362": "Current control for rail pressure control valve",
  "4373": "Air Flow Mass not Plausible",
  "4378": "Rail pressure control valve test (nv)",
  "4382": "Rail pressure control valve actuator test",
  "4390": "(1246) Charge air temperature sensor, signal",
  "4391": "(1245) Charge air temperature sensor, signal",
  "4392": "Charge air temperature sensor, signal",
  "4397": "Quantity control valve actuator test",
  "43A0": "Starter inhibit relay, control",
  "43A1": "Starter inhibit relay, control",
  "43A2": "Starter inhibit relay, control",
  "43A3": "Starter inhibit relay, control",
  "43B0": "Power Stage fault status for System lamp (nv)",
  "43B1": "Power Stage fault status for System lamp (nv)",
  "43B2": "Power Stage fault status for System lamp (nv)",
  "43B3": "Power Stage fault status for System lamp (nv)",
  "43C0": "(2622) Throttle valve actuator, control",
  "43D1": "(2621) Throttle valve actuator, control",
  "43E2": "(2620) Throttle valve actuator, control",
  "43E3": "(0638) Throttle valve actuator, control",
  "43F0": "Electric auxiliary heater, control",
  "43F1": "Electric auxiliary heater, control",
  "43F2": "Electric auxiliary heater, control",
  "43F3": "Electric auxiliary heater, control",
  // 44xx
  "4403": "Control unit internal 17",
  "4410": "Injector cylinder 1, control",
  "4411": "Injector cylinder 1, control",
  "4412": "Injector cylinder 1, control",
  "4413": "Injector cylinder 1, control",
  "4417": "Control master/slave",
  "441A": "Injector cylinder 1, control",
  "441B": "Injector cylinder 1, control",
  "441C": "(0201) Injector cylinder 1, control",
  "441D": "Injector cylinder 1, control",
  "4420": "Injector cylinder 2, control",
  "4421": "Injector cylinder 2, control",
  "4422": "Injector cylinder 2, control",
  "4423": "Injector cylinder 2, control",
  "4428": "Control master/slave",
  "442A": "Injector cylinder 2, control",
  "442B": "Injector cylinder 2, control",
  "442C": "(0202) Injector cylinder 2, control",
  "442D": "Injector cylinder 2, control",
  "4430": "Injector cylinder 3, control",
  "4431": "Injector cylinder 3, control",
  "4432": "Injector cylinder 3, control",
  "4433": "Injector cylinder 3, control",
  "4438": "Control master/slave",
  "443A": "Injector cylinder 3, control",
  "443B": "Injector cylinder 3, control",
  "443C": "(0203) Injector cylinder 3, control",
  "443D": "Injector cylinder 3, control",
  "4440": "Injector cylinder 4, control",
  "4441": "Injector cylinder 4, control",
  "4442": "Injector cylinder 4, control",
  "4443": "Injector cylinder 4, control",
  "444A": "Injector cylinder 4, control",
  "444B": "Injector cylinder 4, control",
  "444C": "(0204) Injector cylinder 4, control",
  "444D": "Injector cylinder 4, control",
  "4450": "Injector cylinder 5, control",
  "4451": "Injector cylinder 5, control",
  "4452": "Injector cylinder 5, control",
  "4453": "Injector cylinder 5, control",
  "445A": "Injector cylinder 5, control",
  "445B": "Injector cylinder 5, control",
  "445C": "(0205) Injector cylinder 5, control",
  "445D": "Injector cylinder 5, control",
  "4460": "Injector cylinder 6, control",
  "4461": "Injector cylinder 6, control",
  "4462": "Injector cylinder 6, control",
  "4463": "Injector cylinder 6, control",
  "446A": "Injector cylinder 6, control",
  "446B": "Injector cylinder 6, control",
  "446C": "(0206) Injector cylinder 6, control",
  "446D": "Injector cylinder 6, control",
  "4473": "Control unit internal 18",
  "4480": "Control unit internal 19",
  "4491": "Control unit internal 20",
  "44A0": "Injectors bank 1, control",
  "44A1": "Injectors bank 1, control",
  "44A2": "Injectors bank 1, control",
  "44A3": "Injectors bank 1, control",
  "44A5": "Zero-quantity adaptation injector cylinder 1",
  "44A6": "Zero-quantity adaptation injector cylinder 1",
  "44A7": "Zero-quantity adaptation injector cylinder 1",
  "44A8": "Zero-quantity adaptation injector cylinder 1",
  "44AA": "Injectors bank 1, control",
  "44AB": "Injectors bank 1, control",
  "44AC": "Injectors bank 1, control",
  "44AD": "Injectors bank 1, control",
  "44B0": "Injectors bank 2, control",
  "44B1": "Injectors bank 2, control",
  "44B2": "Injectors bank 2, control",
  "44B3": "Injectors bank 2, control",
  "44B5": "Zero-quantity adaptation injector cylinder 2",
  "44B6": "Zero-quantity adaptation injector cylinder 2",
  "44B7": "Zero-quantity adaptation injector cylinder 2",
  "44B8": "Zero-quantity adaptation injector cylinder 2",
  "44BA": "Injectors bank 2, control",
  "44BB": "Injectors bank 2, control",
  "44BC": "Injectors bank 2, control",
  "44BD": "Injectors bank 2, control",
  "44C0": "Number of requested injections limited",
  "44C1": "Number of requested injections limited",
  "44C2": "Number of requested injections limited",
  "44C5": "Zero-quantity adaptation injector cylinder 3",
  "44C6": "Zero-quantity adaptation injector cylinder 3",
  "44C7": "Zero-quantity adaptation injector cylinder 3",
  "44C8": "Zero-quantity adaptation injector cylinder 3",
  "44D0": "Alternator",
  "44D2": "Alternator",
  "44D3": "Alternator",
  "44D5": "Zero-quantity adaptation injector cylinder 4",
  "44D6": "Zero-quantity adaptation injector cylinder 4",
  "44D7": "Zero-quantity adaptation injector cylinder 4",
  "44D8": "Zero-quantity adaptation injector cylinder 4",
  "44E2": "Alternator",
  "44E3": "Alternator",
  "44E5": "Zero-quantity adaptation injector cylinder 5",
  "44E6": "Zero-quantity adaptation injector cylinder 5",
  "44E7": "Zero-quantity adaptation injector cylinder 5",
  "44E8": "Zero-quantity adaptation injector cylinder 5",
  "44F0": "Rail pressure plausibility, pressure-controlled (nv)",
  "44F5": "Zero-quantity adaptation injector cylinder 6",
  "44F6": "Zero-quantity adaptation injector cylinder 6",
  "44F7": "Zero-quantity adaptation injector cylinder 6",
  "44F8": "Zero-quantity adaptation injector cylinder 6",
  // 45xx
  "4500": "EGR - Deviation",
  "4501": "(0401) EGR control, control deviation",
  "4506": "EGR - Deviation",
  "4507": "(0402) EGR control, control deviation",
  "4512": "Thermal oil level sensor, signal",
  "4513": "Thermal oil level sensor, signal",
  "4521": "(1296) Boost pressure control, control deviation",
  "452A": "DPF System",
  "4530": "(1297) Boost pressure control, control deviation",
  "4536": "Power Management",
  "453B": "PT Can Bus",
  "453C": "PT Can Bus",
  "453D": "PT Can Bus",
  "4541": "Thermal oil level sensor",
  "454B": "Private CAN bus(master)",
  "454C": "Private CAN bus(master)",
  "454D": "Private CAN bus(master)",
  "4550": "Boost Pressure Modulation 2",
  "4560": "(3002) Rail pressure plausibility, quantity-controlled",
  "4570": "Rail pressure plausibility, quantity-controlled",
  "4580": "(3003) Rail pressure plausibility, quantity-controlled",
  "4587": "Fuel Filter",
  "4590": "Rail pressure plausibility, quantity-controlled",
  "45A0": "(3004) Rail pressure plausibility, quantity-controlled",
  "45A5": "Boost Air Temp Sensor 2 - Signal",
  "45A6": "Boost Air Temp Sensor 2 - Signal",
  "45C0": "Rail pressure plausibility, quantity-controlled (nv)",
  "45E3": "Master/slave monitoring",
  "45F2": "Master/slave monitoring",
  "45F3": "Master/slave monitoring",
  // 46xx
  "4600": "(3005) Rail pressure plausibility, pressure-controlled",
  "4605": "Particulate filter system",
  "4610": "Rail pressure plausibility, pressure-controlled",
  "4618": "Ambient pressure sensor (in control unit)",
  "4620": "(3006) Rail pressure plausibility, pressure-controlled",
  "4628": "Particulate filter system",
  "4630": "Rail pressure plausibility, pressure-controlled",
  "4640": "Rail pressure plausibility, pressure-controlled",
  "4645": "EGR actuator",
  "4650": "Rail pressure plausibility, pressure-controlled (nv)",
  "4656": "Control unit internal 24",
  "4660": "Supply voltage",
  "4661": "Supply voltage",
  "4665": "Particulate filter system",
  "4666": "Particulate filter system",
  "4667": "Particulate filter system",
  "4670": "(0643) Feed voltage 1",
  "4671": "(0642) Feed voltage 1",
  "4677": "Throttle valve actuator",
  "4680": "(0653) Feed voltage 2",
  "4681": "(0652) Feed voltage 2",
  "4687": "Throttle valve actuator",
  "4690": "Feed voltage 3",
  "4691": "Feed voltage 3",
  "4697": "Throttle valve actuator",
  "46A0": "Control unit internal 1",
  "46A1": "Control unit internal 1",
  "46A2": "Control unit internal 1",
  "46A3": "Control unit internal 1",
  "46A7": "Swirl flap actuator",
  "46B0": "Control unit internal 2",
  "46B1": "Control unit internal 2",
  "46B2": "Control unit internal 2",
  "46B3": "Control unit internal 2",
  "46B7": "Swirl flap actuator",
  "46C0": "Control unit internal 3",
  "46C1": "Control unit internal error 3",
  "46C2": "Control unit internal error 3",
  "46C3": "Control unit internal error 3",
  "46C7": "Swirl flap actuator",
  "46D0": "Control unit internal 4",
  "46D1": "Control unit internal 4",
  "46D2": "Control unit internal 4",
  "46D3": "Control unit internal 4",
  "46D5": "Compressor Bypass Activation",
  "46D6": "Compressor Bypass Activation",
  "46D7": "Compressor Bypass Activation",
  "46D8": "Compressor Bypass Activation",
  "46E0": "Control unit internal error 5",
  "46E1": "Control unit internal error 5",
  "46E2": "Control unit internal error 5",
  "46E3": "Control unit internal error 5",
  "46E5": "Wastegate Valve Activation",
  "46E6": "Wastegate Valve Activation",
  "46F0": "Control unit internal error 6",
  "46F1": "Control unit internal error 6",
  "46F2": "Control unit internal error 6",
  "46F3": "Control unit internal error 6",
  // 47xx
  "4700": "Control unit internal error 7",
  "4701": "Control unit internal error 7",
  "4702": "Control unit internal error 7",
  "4703": "Control unit internal 7",
  "4707": "Wastegate Valve Activation",
  "4708": "Wastegate Valve Activation",
  "4710": "Control unit internal error 8",
  "4711": "Control unit internal 8",
  "4712": "Control unit internal 8",
  "4713": "Control unit internal 8",
  "4720": "Control unit internal error 9",
  "4721": "Control unit internal error 9",
  "4722": "Control unit internal error 9",
  "4723": "Control unit internal 9",
  "4730": "Quantity control valve current control",
  "4731": "Quantity control valve current control",
  "4732": "Quantity control valve current control",
  "4740": "Control unit internal 11",
  "4747": "Injectors - Amplifier Adjustment(control-unit internal)",
  "4750": "Control unit internal 12",
  "4753": "Control unit internal 12",
  "475A": "Exhaust Backpressure Sensor - Bank 2",
  "475B": "Exhaust Backpressure Sensor - Bank 2",
  "4763": "Control unit internal 13 (nv)",
  "4765": "Injector Cyl 1 - Activation",
  "4766": "Injector Cyl 1 - Activation",
  "4767": "Injector Cyl 1 - Activation",
  "4768": "Injector Cyl 1 - Activation",
  "476A": "Injector Cyl 4/5/6 Buffer Voltage Measurement(control-unit internal)",
  "476B": "Injector Cyl 4/5/6 Buffer Voltage Measurement(control-unit internal)",
  "4770": "Control unit internal error 14",
  "4771": "Control unit internal error 14",
  "4772": "Control unit internal 14",
  "4773": "Control unit internal 14",
  "477C": "Injectors Activation Duration(control-unit internal)",
  "4780": "Control unit internal 15",
  "4781": "Control unit internal 15",
  "4782": "Control unit internal 15",
  "4783": "Control unit internal 15",
  "4785": "Injector Cyl 2 - Activation",
  "4786": "Injector Cyl 2 - Activation",
  "4787": "Injector Cyl 2 - Activation",
  "4788": "Injector Cyl 2 - Activation",
  "478C": "Injector Activation Duration(control-unit internal)",
  "4792": "Master/slave monitoring",
  "4793": "Master/slave monitoring",
  "4795": "Injector Cyl 3 - Activation",
  "4796": "Injector Cyl 3 - Activation",
  "4797": "Injector Cyl 3 - Activation",
  "4798": "Injector Cyl 3 - Activation",
  "47A0": "MFC error path for Misfire cylinder 0 (nv)",
  "47A5": "Injector Cyl 4 - Activation",
  "47A6": "Injector Cyl 4 - Activation",
  "47A7": "Injector Cyl 4 - Activation",
  "47A8": "Injector Cyl 4 - Activation",
  "47AB": "Private CAN Bus(Slave)",
  "47AC": "Private CAN Bus(Slave)",
  "47AD": "Private CAN Bus(Slave)",
  "47B0": "MFC error path for Misfire cylinder 1 (nv)",
  "47B5": "Injector Cyl 5 - Activation",
  "47B6": "Injector Cyl 5 - Activation",
  "47B7": "Injector Cyl 5 - Activation",
  "47B8": "Injector Cyl 5 - Activation",
  "47BB": "Power Train CAN Bus(Slave)",
  "47BC": "Power Train CAN Bus(Slave)",
  "47BD": "Power Train CAN Bus(Slave)",
  "47C0": "MFC error path for Misfire cylinder 2 (nv)",
  "47C5": "Injector Cyl 6 - Activation",
  "47C6": "Injector Cyl 6 - Activation",
  "47C7": "Injector Cyl 6 - Activation",
  "47C8": "Injector Cyl 6 - Activation",
  "47D0": "MFC error path for Misfire cylinder 3 (nv)",
  "47D5": "Injector Cyl 7 - Activation",
  "47D6": "Injector Cyl 7 - Activation",
  "47D7": "Injector Cyl 7 - Activation",
  "47D8": "Injector Cyl 7 - Activation",
  "47E0": "MFC error path for Misfire cylinder 4 (nv)",
  "47E5": "Injector Cyl 8 - Activation",
  "47E6": "Injector Cyl 8 - Activation",
  "47E7": "Injector Cyl 8 - Activation",
  "47E8": "Injector Cyl 8 - Activation",
  "47F0": "MFC error path for Misfire cylinder 5 (nv)",
  // 48xx
  "4803": "Torque Control ACC",
  "480A": "DPF - Bank 1",
  "4810": "Torque Control ACC",
  "481A": "DPF - Bank 1",
  "4820": "(1557) A/C power output, control",
  "4821": "(1556) A/C power output, control",
  "4822": "(1555) A/C power output, control",
  "4823": "A/C power output, control",
  "4830": "Intake air temperature sensor",
  "4831": "Intake air temperature sensor",
  "4832": "Intake air temperature sensor",
  "483D": "Throttle Actuator",
  "4841": "(1491) EGR control 2, control deviation",
  "484A": "Accelerator Pedal Potentiometer - Signal",
  "4850": "(1492) EGR control 2, control deviation",
  "4857": "Swirl flap actuator",
  "4863": "Cruise control",
  "4867": "Swirl flap actuator",
  "486D": "Control Unit Software Fault",
  "4870": "Misfire detection in multiple cylinders",
  "4877": "Swirl flap actuator",
  "487A": "O2 sensor Bank 2 - Bias Voltage",
  "487B": "O2 sensor Bank 2 - Bias Voltage",
  "487C": "O2 sensor Bank 2 - Bias Voltage",
  "4880": "Misfire detection cylinder 1",
  "4887": "Swirl flap actuator",
  "488A": "O2 sensor Bank 2 - Pump Current",
  "488B": "O2 sensor Bank 2 - Pump Current",
  "488C": "O2 sensor Bank 2 - Pump Current",
  "4890": "Misfire detection cylinder 2",
  "4896": "Swirl flap actuator",
  "489A": "O2 sensor Bank 2 - Virtual Ground",
  "489B": "O2 sensor Bank 2 - Virtual Ground",
  "489C": "O2 sensor Bank 2 - Virtual Ground",
  "48A2": "Message (ASC1)",
  "48A3": "Message (ASC1)",
  "48B2": "Message (ASC2)",
  "48B3": "Message (ASC2)",
  "48B5": "Injectors Voltage Measurement(control-unit internal)",
  "48B6": "Injectors Voltage Measurement(control-unit internal)",
  "48B7": "Injectors Voltage Measurement(control-unit internal)",
  "48BC": "O2 sensor Bank 2",
  "48C2": "Message (EGS1)",
  "48C3": "Message (EGS1)",
  "48C5": "Injectors Voltage Measurement(control-unit internal)",
  "48C6": "Injectors Voltage Measurement(control-unit internal)",
  "48C7": "Injectors Voltage Measurement(control-unit internal)",
  "48CA": "O2 sensor Bank 2",
  "48CB": "O2 sensor Bank 2",
  "48D2": "Message (INSTR2)",
  "48D3": "Message (INSTR2)",
  "48DA": "Control Unit Internal 25",
  "48DB": "Control Unit Internal 25",
  "48E2": "Message (INSTR3)",
  "48E3": "Message (INSTR3)",
  "48EA": "Control Unit Internal 26",
  "48EB": "Control Unit Internal 26",
  "48F2": "(3200) CAN Bus A",
  "48F3": "(3201) CAN Bus A",
  "48F7": "Injectors Wiring Loom",
  "48FD": "Control Unit Internal 27",
  // 49xx
  "4900": "Torque intervention DSC (nv)",
  "4907": "Injectors Selector Switch(control-unit internal)",
  "490B": "Control Unit Internal 28",
  "4912": "(3200) CAN Bus B",
  "4913": "(3201) CAN Bus B",
  "4917": "Injectors Charge Switch(control-unit internal)",
  "4920": "Torque intervention transmission (nv)",
  "4925": "Throttle Valve Actuator 2 Activation",
  "492A": "O2 sensor Bank 2 Heater",
  "492B": "O2 sensor Bank 2 Heater",
  "4930": "Misfire detection cylinder 3",
  "4936": "Throttle Valve Actuator 2 Activation",
  "493D": "O2 sensor Bank 2",
  "4940": "Misfire detection cylinder 4",
  "4947": "Throttle Valve Actuator 2 Activation",
  "4948": "Throttle Valve Actuator 2 Activation",
  "494D": "O2 sensor Bank 2",
  "4950": "Misfire detection cylinder 5",
  "4957": "Throttle Valve Actuator 2",
  "495A": "Exhaust Temp Sensor before DPF Bank 2",
  "495B": "Exhaust Temp Sensor before DPF Bank 2",
  "4960": "Misfire detection cylinder 6",
  "4967": "Throttle Valve Actuator 2",
  "496A": "DPF Bank 2",
  "497A": "DPF Bank 2",
  "4991": "Message : Instrument Cluster",
  "4992": "Message : Instrument Cluster",
  "4997": "Throttle Valve Actuator 2",
  "49A2": "Message : Ambient Temperature",
  "49B0": "Message : Torque Request",
  "49C0": "Message : Torque Request",
  "49D2": "Message : Torque Request",
  "49D7": "Message (ASC4)",
  "49D8": "Message (ASC4)",
  "49E0": "Message : Torque Request",
  "49E7": "Throttle valve actuator",
  "49F2": "Message : Vehicle Speed",
  "49F3": "Message : Vehicle Speed",
  "49F7": "Swirl flap actuator",
  // 4Axx
  "4A02": "Terminal 15",
  "4A03": "Terminal 15",
  "4A07": "Alternator",
  "4A08": "Alternator",
  "4A10": "Bit-serial data interface BSD",
  "4A13": "Bit-serial data interface BSD",
  "4A15": "Alternator",
  "4A17": "Alternator",
  "4A18": "Alternator",
  "4A22": "Boost Air Pressure Actuator 2 Activation",
  "4A23": "Boost Air Pressure Actuator 2 Activation",
  "4A25": "Intelligent Battery Sensor",
  "4A27": "Intelligent Battery Sensor",
  "4A28": "Intelligent Battery Sensor",
  "4A30": "Multifunction steering wheel, signal",
  "4A31": "Multifunction steering wheel, signal",
  "4A32": "Multifunction steering wheel, signal",
  "4A33": "Multifunction steering wheel, signal",
  "4A35": "Intelligent Battery Sensor",
  "4A37": "Intelligent Battery Sensor",
  "4A38": "Intelligent Battery Sensor",
  "4A41": "EWS interface fault",
  "4A42": "EWS interface fault",
  "4A43": "EWS interface fault",
  "4A45": "Intelligent Battery Sensor",
  "4A47": "Intelligent Battery Sensor",
  "4A48": "Intelligent Battery Sensor",
  "4A50": "EWS EEPROM rolling-code storage faulty",
  "4A51": "EWS EEPROM rolling-code storage faulty",
  "4A56": "Power Management Battery",
  "4A58": "Power Management Battery",
  "4A60": "EWS manipulation",
  "4A61": "EWS manipulation",
  "4A62": "EWS manipulation",
  "4A63": "EWS manipulation",
  "4A65": "Power Management Vehicle Electrical System",
  "4A66": "Power Management Vehicle Electrical System",
  "4A67": "Power Management Vehicle Electrical System",
  "4A70": "Map FMTC_trq2qBas_MAP incorrect",
  "4A80": "Charge air hose monitoring",
  "4A92": "Message (ASC3)",
  "4A93": "Message (ASC3)",
  "4AA2": "Message (EGS2)",
  "4AA3": "Message (EGS2)",
  "4AB0": "Electric auxiliary heater",
  "4AB2": "Electric auxiliary heater",
  "4AC0": "Electric auxiliary heater 2 (nv)",
  "4AC2": "Electric auxiliary heater 2 (nv)",
  "4AD0": "Electric auxiliary heater 3 (nv)",
  "4AD2": "Electric auxiliary heater 3 (nv)",
  "4AD5": "Zero-quantity adaptation injector cylinder 1",
  "4AD6": "Zero-quantity adaptation injector cylinder 1",
  "4AE0": "E-box fan, control",
  "4AE1": "E-box fan, control",
  "4AE2": "E-box fan, control",
  "4AE3": "E-box fan, control",
  "4AE5": "Zero-quantity adaptation injector cylinder 2",
  "4AE6": "Zero-quantity adaptation injector cylinder 2",
  "4AF0": "Control unit temperature sensor, signal",
  "4AF1": "Control unit temperature sensor, signal",
  "4AF5": "Zero-quantity adaptation injector cylinder 3",
  "4AF6": "Zero-quantity adaptation injector cylinder 3",
  // 4Bxx
  "4B00": "Control unit temperature",
  "4B05": "Zero-quantity adaptation injector cylinder 4",
  "4B06": "Zero-quantity adaptation injector cylinder 4",
  "4B10": "(1278) Smooth-running controller",
  "4B11": "(1279) Smooth-running controller",
  "4B15": "Zero-quantity adaptation injector cylinder 5",
  "4B16": "Zero-quantity adaptation injector cylinder 5",
  "4B20": "Electric fan",
  "4B22": "Electric fan",
  "4B25": "Zero-quantity adaptation injector cylinder 6",
  "4B26": "Zero-quantity adaptation injector cylinder 6",
  "4B30": "Electric fan 2 (nv)",
  "4B32": "Electric fan 2 (nv)",
  "4B35": "Oil Sensor",
  "4B36": "Oil Sensor",
  "4B37": "Oil Sensor",
  "4B38": "Oil Sensor",
  "4B40": "Electric fan 3 (nv)",
  "4B42": "Electric fan 3 (nv)",
  "4B45": "Injector Cyl 1 Energy Consumption Measurement",
  "4B50": "Quantity balancing",
  "4B55": "Injector Cyl 2 Energy Consumption Measurement",
  "4B60": "Quantity drift compensation",
  "4B65": "Injector Cyl 3 Energy Consumption Measurement",
  "4B75": "Injector Cyl 4 Energy Consumption Measurement",
  "4B80": "Rail pressure plausibility, quantity-controlled (nv)",
  "4B85": "Injector Cyl 5 Energy Consumption Measurement",
  "4B90": "Rail pressure monitoring at engine start",
  "4B95": "Injector Cyl 6 Energy Consumption Measurement",
  "4BA0": "(0113) Intake air temperature sensor, signal",
  "4BA1": "(0112) Intake air temperature sensor, signal",
  "4BB0": "(3269) Supply voltage mass air flow sensor (MAF)",
  "4BB1": "(3270) Supply voltage mass air flow sensor (MAF)",
  "4BB5": "(3273) Mass air flow sensor (MAF)",
  "4BB6": "(3274) Mass air flow sensor (MAF)",
  "4BB7": "Mass air flow sensor (MAF)",
  "4BC0": "(0102) Mass air flow sensor (MAF)",
  "4BC1": "(0103) Mass air flow sensor (MAF)",
  "4BC2": "(0101) Mass air flow sensor (MAF)",
  "4BC5": "Intake air temp sensor (reference signal for MAF)",
  "4BC6": "Intake air temp sensor (reference signal for MAF)",
  "4BC7": "Intake air temp sensor (reference signal for MAF)",
  "4BD2": "Torque request ARS",
  "4BD5": "Engine mount, control",
  "4BD6": "Engine mount, control",
  "4BD7": "Engine mount, control",
  "4BD8": "Engine mount, control",
  "4BE2": "Message : Transmission data",
  "4BE7": "Message : Transmission data 2",
  "4BF2": "Message : Air Conditioning",
  "4BF7": "Message : Range",
  // 4Cxx
  "4C00": "Message : Cruise Control",
  "4C01": "Message : Cruise Control",
  "4C02": "Message : Cruise Control",
  "4C06": "Message : ARS Status",
  "4C07": "Message : ARS Status",
  "4C12": "Message : DSC Status",
  "4C15": "Message : Terminal 15",
  "4C16": "Message : Terminal 15",
  "4C17": "Message : Terminal 15",
  "4C20": "Message : DSC Torque",
  "4C21": "Message : DSC Torque",
  "4C22": "Message : DSC Torque",
  "4C23": "Message : DSC Torque",
  "4C27": "Message : Vehicle Speed",
  "4C28": "Message : Vehicle Speed",
  "4C40": "Particulate filter heater, control",
  "4C41": "Particulate filter heater, control",
  "4C42": "Particulate filter heater, control",
  "4C43": "Particulate filter heater, control",
  "4C45": "Injector Cyl 7 Energy Consumption Measurement",
  "4C55": "Injector Cyl 8 Energy Consumption Measurement",
  "4C65": "Zero Quantity Adaptation Injector 7",
  "4C66": "Zero Quantity Adaptation Injector 7",
  "4C75": "Supply Voltage Air Mass Flow Sensor 2",
  "4C76": "Supply Voltage Air Mass Flow Sensor 2",
  "4C80": "MFC error path for Misfire cylinder 6 (nv)",
  "4C90": "MFC error path for Misfire cylinder 7 (nv)",
  "4C95": "Zero Quantity Adaptation Injector 8",
  "4C96": "Zero Quantity Adaptation Injector 8",
  "4CA2": "Message : Power Management",
  "4CB2": "Message : Power Management",
  "4CB3": "Message : Power Management",
  "4CE0": "Particulate filter system",
  "4CF3": "Exhaust back-pressure sensor, signal",
  // 4Dxx
  "4D00": "Exhaust back-pressure sensor",
  "4D01": "Exhaust back-pressure sensor",
  "4D03": "Exhaust back-pressure sensor",
  "4D13": "Particulate filter system",
  "4D23": "Particulate filter system",
  "4D25": "Exhaust Temp Sensor before Catalytic Converter Bank 2",
  "4D26": "Exhaust Temp Sensor before Catalytic Converter Bank 2",
  "4D40": "Particulate filter system",
  "4D45": "Exhaust Temp Sensor before DPF Bank 2",
  "4D46": "Exhaust Temp Sensor before DPF Bank 2",
  "4D56": "DPF Bank 2",
  "4D65": "DPF System",
  "4D73": "Particulate filter system",
  "4D75": "DPF System",
  "4D81": "Boost Pressure Actuator 2 Activation",
  "4D98": "Exhaust Backpressure Sensor Bank 2",
  "4DA3": "Boost Pressure Control",
  "4DA5": "Exhaust Backpressure Sensor Bank 2",
  "4DA8": "Exhaust Backpressure Sensor Bank 2",
  "4DB0": "EGR Controller 2 Activation",
  "4DC1": "EGR Controller 2 Activation",
  "4DD2": "EGR Controller 2 Activation",
  "4DD3": "EGR Controller 2 Activation",
  "4DD5": "Exhaust Temp Sensor before DPF Bank 2",
  "4DE0": "Monitoring master/slave - Private CAN",
  "4DE1": "Monitoring master/slave - Private CAN",
  "4DE3": "Monitoring master/slave - Private CAN",
  "4DF0": "Message : Transmission Torque",
  "4DF1": "Message : Transmission Torque",
  "4DF2": "Message : Transmission Torque",
  "4DF3": "Message : Transmission Torque",
  "4DF5": "Exhaust Temp Sensor before DPF Bank 2",
  // 5Dxx
  "5D90": "Left Front Wheel Speed Sensor : Accident Recognition",
  "5D91": "Left Front Wheel Speed Sensor : Extrapolation",
  "5D92": "Left Front Wheel Speed Sensor : Periodical Control",
  "5D93": "Left Front Wheel Speed Sensor : Accident Recognition",
  "5D94": "Left Front Wheel Speed Sensor : Long Term Control",
  "5DA0": "Right Front Wheel Speed Sensor : Accident Recognition",
  "5DA1": "Right Front Wheel Speed Sensor : Extrapolation",
  "5DA2": "Right Front Wheel Speed Sensor : Periodical Control",
  "5DA3": "Right Front Wheel Speed Sensor : Accident Recognition",
  "5DA4": "Right Front Wheel Speed Sensor : Long Term Control",
  "5DB0": "Left Rear Wheel Speed Sensor : Accident Recognition",
  "5DB1": "Left Rear Wheel Speed Sensor : Extrapolation",
  "5DB2": "Left Rear Wheel Speed Sensor : Periodical Control",
  "5DB3": "Left Rear Wheel Speed Sensor : Accident Recognition",
  "5DB4": "Left Rear Wheel Speed Sensor : Long Term Control",
  "5DC0": "Right Rear Wheel Speed Sensor : Accident Recognition",
  "5DC1": "Right Rear Wheel Speed Sensor : Extrapolation",
  "5DC2": "Right Rear Wheel Speed Sensor : Periodical Control",
  "5DC3": "Right Rear Wheel Speed Sensor : Accident Recognition",
  "5DC4": "Right Rear Wheel Speed Sensor : Long Term Control",
  "5DF0": "Pump Motor",
  "5DF2": "Internal Error, Valve/ECU Hardware Error, ROM/RAM Check",
  "5DF4": "Power Supply too Low",
  "5DF5": "Control Unit Internal Error",
  "5DF7": "Power Supply too High",
  // 5Exx
  "5E00": "Tyre Test Active",
  "5E01": "Tyre Test Timeout",
  "5E02": "Tyre Test Gyration Sensor Justification Error",
  "5E03": "Tyre Test Gyration Sensor Error",
  "5E04": "Tyre Test Lateral Acceleration Sensor Error",
  "5E05": "Tyre test Lateral Acceleration Sensor Error and Gyration Sensor",
  "5E06": "Tyre Test Gyration Sensor Fault",
  "5E07": "Tyre Test Lateral Acceleration Sensor Error and Gyration Sensor Fault",
  "5E08": "Tyre Test Steering Angle Sensor Error",
  "5E11": "Internal Error CAN-Controller",
  "5E14": "CAN Timeout DME/DDE",
  "5E15": "CAN Timeout EGS",
  "5E16": "CAN Timeout Instrument Cluster",
  "5E18": "CAN DME/DDE Message",
  "5E19": "CAN DME/DDE Torque Reduction Not Possible",
  "5E1A": "CAN DME/DDE Signal Error",
  "5E1E": "CAN Timeout LWS",
  "5E1F": "Steering Angle Sensor – not Initialised",
  "5E20": "Pressure Sensor 1 Accident Recognition",
  "5E21": "Pressure Sensor 2 Accident Recognition",
  "5E24": "Pressure Sensor 1/2 not Plausible",
  "5E26": "Sensor Power Supply",
  "5E2F": "Temperature Sensor",
  "5E30": "Lateral Acceleration Sensor Accident Recognition",
  "5E32": "Lateral Acceleration Signal not Plausible",
  "5E38": "Wheel Speed Sensor Accident Recognition",
  "5E3C": "Wheel Speed not Plausible",
  "5E40": "Lateral Acceleration Signal not Plausible, Offset",
  "5E43": "Lateral Acceleration Internal Error",
  "5E4E": "DSC Sensor Offset Check",
  "5E4F": "Long Time Regulation DSC",
  "5E59": "Coding Error",
  "5E5B": "Switch Pressed Longer than 10s or Faulty",
  "5E5D": "Brake Fluid Level Switch",
  "5E5E": "Brake Light Switch",
  // 70xx
  "7073": "Automatic Gearbox Switch Signal",
  // CDxx
  "CD87": "PT-CAN communication fault",
  "CD8B": "Local-CAN communication fault",
  "CD94": "Message missing (outside temperature, 0x310)",
  "CD95": "Message missing (cruise/ACC operation, 0x194)",
  "CD96": "Message missing (torque request ACC, 0xB7)",
  "CD97": "Message missing (torque request AFS, 0xB9)",
  "CD98": "Message missing (torque request DSC, 0xB6)",
  "CD99": "Message missing (torque request EGS, 0xB5)",
  "CD9A": "Message missing (torque request SMG, 0xBD)",
  "CD9B": "Message missing (vehicle mode, 0x315)",
  "CD9C": "Message missing (speed, 0x1A0)",
  "CD9D": "Message missing (transmission data, 0xBA)",
  "CD9F": "Message missing (odometer, 0x330)",
  "CDA0": "Message missing (terminal status, 0x130)",
  "CDA1": "Message missing (steering angle, 0xC4)",
  "CDA2": "Message missing (power mgmt battery voltage, 0x3B4)",
  "CDA3": "Message missing (power mgmt charging voltage, 0x334)",
  "CDA4": "Message missing (ARS module status, 0x1AC)",
  "CDA5": "Message missing (DSC status, 0x19E)",
  "CDA6": "Message missing (fuel pump status, 0x335)",
  "CDA7": "Message missing (reverse gear, 0x3B0)",
  "CDA8": "Message missing (instrument cluster status, 0x1B4)",
  "CDA9": "Message missing (A/C status, 0x1B5)",
  // FFxx
  "FFFF": "Unknown fault location",
};
window.BMW_FAULT_PHRASES = {
  "AUC Heizung": "AUC sensor heater",
  "AUC Sensor": "AUC air-quality sensor",
  "Abgasklappe": "Exhaust flap",
  "BLS-BTS-Plausibilisierung": "Brake light / brake test switch: plausibility",
  "Belueftungsklappenmotor": "Ventilation flap motor",
  "CAN bus_off": "CAN bus off",
  "Drosselklappensensor 1": "Throttle position sensor 1",
  "Drosselklappensensor 2": "Throttle position sensor 2",
  "Drucksensor": "Refrigerant pressure sensor",
  "Drucksensor, AUC Versorgung": "Refrigerant pressure sensor / AUC supply",
  "E-Luefter": "Electric fan",
  "EWS-Code": "EWS code",
  "EWS-Uebertragung/-Parity": "EWS transfer / parity",
  "Einspritzventil Zylinder 1": "Injector, cylinder 1",
  "Einspritzventil Zylinder 2": "Injector, cylinder 2",
  "Einspritzventil Zylinder 3": "Injector, cylinder 3",
  "Einspritzventil Zylinder 4": "Injector, cylinder 4",
  "Einspritzventil Zylinder 5": "Injector, cylinder 5",
  "Einspritzventil Zylinder 6": "Injector, cylinder 6",
  "Endstufen-Fehler": "Output stage fault",
  "Endstufenfehler DMTL-Pumpe": "Output stage fault: DMTL pump",
  "Endstufenfehler DMTL-Ventil": "Output stage fault: DMTL valve",
  "Energiesparmode aktiv": "Energy-saving mode active",
  "Energiesparmode aktiviert": "Energy-saving mode activated",
  "Entfrostungsklappenmotor": "Defrost flap motor",
  "Falscher Klimakasten verbaut": "Wrong A/C housing fitted",
  "Falsches Klimageraet IHKR": "Wrong A/C unit fitted (IHKR)",
  "Fehler Sekundaerluftmassenmesser": "Secondary air mass flow sensor: fault",
  "Fehler Variante Drucksensor erkennen": "Pressure sensor variant detection: fault",
  "Frischluft/Umluftklappenmotor links": "Fresh-air/recirc flap motor, left",
  "Frischluft/Umluftklappenmotor rechts": "Fresh-air/recirc flap motor, right",
  "Functional Check TEV": "Functional check: purge valve (TEV)",
  "Fussraumklappenmotor": "Footwell flap motor",
  "Geblaesesteuerspannung": "Blower control voltage",
  "Hauptrelais": "Main relay",
  "Innenfuehlergeblaese": "Interior-sensor aspirator blower",
  "Innenraumtemperaturfuehler": "Interior temperature sensor",
  "KW - Fehler": "Crankshaft sensor (KW): fault",
  "Kat-Wirkungsgrad bei Anspringzeit Bk1": "Catalyst efficiency at light-off, bank 1",
  "Kat-Wirkungsgrad bei Anspringzeit Bk2": "Catalyst efficiency at light-off, bank 2",
  "Katalysatorwirkungsgrad Hauptkatalysator Bank 1": "Main catalyst efficiency, bank 1",
  "Katalysatorwirkungsgrad Hauptkatalysator Bank 2": "Main catalyst efficiency, bank 2",
  "Klopfsensor 1": "Knock sensor 1",
  "Klopfsensor 2": "Knock sensor 2",
  "Kommunikation mit dem Zuheizer": "Communication with auxiliary heater",
  "Kraftstoffpumpenrelais": "Fuel pump relay",
  "Kuehlerausgangstemperatur": "Radiator outlet temperature",
  "Kupplungsschalter defekt": "Clutch switch faulty",
  "LLFS Fehler in der Mechanik": "Idle actuator: mechanical fault",
  "LLFS oeffnende Spule elektrisch": "Idle actuator, opening coil: electrical",
  "LLFS schliessende Spule elektrisch": "Idle actuator, closing coil: electrical",
  "LM_HFM": "Mass air flow (hot-film) signal",
  "LS1-Betriebsbereitschaft waehrend aktivem LR": "O2 sensor 1: readiness during active lambda control",
  "LS2-Betriebsbereitschaft waehrend aktivem LR": "O2 sensor 2: readiness during active lambda control",
  "Lambdaregelgrenze Bank1": "Lambda control limit, bank 1",
  "Lambdaregelgrenze Bank2": "Lambda control limit, bank 2",
  "Lambdaregelung nach vorgegebener Zeit nicht aktiv": "Lambda control not active within set time",
  "Lambdareglerabweichung Bank 1": "Lambda controller deviation, bank 1",
  "Lambdareglerabweichung Bank 2": "Lambda controller deviation, bank 2",
  "Lambdasondenheizung Bank 1": "O2 sensor heater, bank 1",
  "Lambdasondenheizung Bank 2": "O2 sensor heater, bank 2",
  "Lambdasondenheizung Nach-KAT-Sonde 1": "O2 sensor heater, post-cat sensor 1",
  "Lambdasondenheizung Nach-KAT-Sonde 2": "O2 sensor heater, post-cat sensor 2",
  "Lambdasondenheizung Vor-KAT-Sonde 1": "O2 sensor heater, pre-cat sensor 1",
  "Lambdasondenheizung Vor-KAT-Sonde 2": "O2 sensor heater, pre-cat sensor 2",
  "Lambdasondenheizung nach Kat Bank 1": "O2 sensor heater, post-cat, bank 1",
  "Lambdasondenheizung nach Kat Bank 2": "O2 sensor heater, post-cat, bank 2",
  "Lambdasondenspannung Nach-KAT-Sonde 1": "O2 sensor voltage, post-cat sensor 1",
  "Lambdasondenspannung Nach-KAT-Sonde 2": "O2 sensor voltage, post-cat sensor 2",
  "Lambdasondenspannung Vor-KAT-Sonde 1": "O2 sensor voltage, pre-cat sensor 1",
  "Lambdasondenspannung Vor-KAT-Sonde 2": "O2 sensor voltage, pre-cat sensor 2",
  "Lambdatrimmregelung Nach-Kat-Bank 2": "Lambda trim control, post-cat, bank 2",
  "Lambdatrimmregelung Vor-Kat-Bank 1": "Lambda trim control, pre-cat, bank 1",
  "Lambdatrimmregelung Vor-Kat-Bank 2": "Lambda trim control, pre-cat, bank 2",
  "Latentwaermespeicher Absperrventil": "Latent-heat-accumulator shutoff valve",
  "Latentwaermespeicher Temperaturfuehler": "Latent-heat-accumulator temperature sensor",
  "Latentwaermespeicher Umschaltventil": "Latent-heat-accumulator changeover valve",
  "Leerlaufdrehzahl": "Idle speed",
  "Luftmassenmesser": "Mass air flow sensor (MAF)",
  "MFL-Toggle-Bit": "Steering-wheel buttons (MFL): toggle bit",
  "MFL-Wipptaster": "Steering-wheel rocker switch (MFL)",
  "MFL-redundante Codierung des Signals": "Steering-wheel buttons (MFL): redundant signal coding",
  "MTC-Lageregler PI-Summenpruefung": "Throttle actuator (MTC): PI checksum",
  "MTC-Lageregler Regeldifferenz": "Throttle actuator (MTC): control deviation",
  "Modulfehler DMTL": "DMTL module fault",
  "Momentenbegrenzung Sicherheitskonzept Ebene1": "Torque limitation, safety concept level 1",
  "Monitoring ERR_TQI_AV_MON": "Monitoring: torque (TQI_AV) plausibility",
  "Monitoring ERR_TQI_N_MAX_MON": "Monitoring: torque at max speed (TQI_N_MAX)",
  "Monitoring ERR_TQI_N_MAX_NVMY_MON": "Monitoring: torque at max speed (TQI_N_MAX_NVMY)",
  "Monitoring Steuergeraete Selbsttest 1": "Monitoring: control unit self-test 1",
  "Monitoring Steuergeraete Selbsttest 2": "Monitoring: control unit self-test 2",
  "Monitoring Steuergeraete Selbsttest 4": "Monitoring: control unit self-test 4",
  "Monitoring Steuergeraete Selbsttest 5": "Monitoring: control unit self-test 5",
  "Monitoring Steuergeraete Selbsttest 6": "Monitoring: control unit self-test 6",
  "Monitoring Steuergeraete Selbsttest 7": "Monitoring: control unit self-test 7",
  "Motordrehzahl": "Engine speed",
  "NKAT-Sonde, Sondesignal nach SA unplausibel BK1": "Post-cat O2 sensor signal after secondary air implausible, bank 1",
  "NKAT-Sonde, Sondesignal nach SA unplausibel BK2": "Post-cat O2 sensor signal after secondary air implausible, bank 2",
  "NKAT-Sondenspannung, Sonde zu langsam BK1": "Post-cat O2 sensor voltage, sensor too slow, bank 1",
  "NKAT-Sondenspannung, Sonde zu langsam BK2": "Post-cat O2 sensor voltage, sensor too slow, bank 2",
  "NW_A - Fehler": "Exhaust camshaft (NW_A): fault",
  "NW_E- Fehler": "Intake camshaft (NW_E): fault",
  "Nach-Kat-Sonde, Aktivitaetsueberpruefung BK1 (Sonde 3)": "Post-cat O2 sensor, activity check, bank 1 (sensor 3)",
  "Nach-Kat-Sonde, Aktivitaetsueberpruefung BK2 (Sonde 4)": "Post-cat O2 sensor, activity check, bank 2 (sensor 4)",
  "PVS-Plausibilitaet": "Pedal sensor (PVS): plausibility",
  "PVS_RATIO": "Pedal sensor (PVS): ratio",
  "Pedalwertsensor 1": "Accelerator pedal sensor 1",
  "Pedalwertsensor 2": "Accelerator pedal sensor 2",
  "Plausibilitaet Abstellzeit": "Engine-off time: plausibility",
  "Plausibilitaet Ansauglufttemperatur": "Intake air temperature: plausibility",
  "Plausibilitaet Kuehlerauslasstemperatur": "Radiator outlet temperature: plausibility",
  "Plausibilitaet Motorkuehlwassertemperatur": "Engine coolant temperature: plausibility",
  "Plausibilitaet Tankfuellstand": "Fuel level: plausibility",
  "Plausibilitaet Umgebungstemperatur": "Ambient temperature: plausibility",
  "Regelfrequenz Lambdasonde Bank 1": "O2 sensor control frequency, bank 1",
  "Regelfrequenz Lambdasonde Bank 2": "O2 sensor control frequency, bank 2",
  "Regelvanos mech. Auslass schwergaengig oder blockiert": "VANOS, exhaust: stiff or blocked",
  "Regelvanos mech. Einlass schwergaengig oder blockiert": "VANOS, intake: stiff or blocked",
  "Regelvanos mechanisch Auslass": "VANOS, exhaust: mechanical",
  "Regelvanos mechanisch Einlass": "VANOS, intake: mechanical",
  "Relais Heckscheibenheizung": "Rear-window heating relay",
  "Relais Klimakompressor": "A/C compressor relay",
  "Relais Sekundaerluftpumpe": "Secondary air pump relay",
  "SA-Durchsatz zu gering": "Secondary air flow too low",
  "SA-Durchsatz zu gross": "Secondary air flow too high",
  "SAV oder SA-Schlauch blockiert": "Secondary air valve or hose blocked",
  "SSG-Eingriff unplausibel": "SMG (SSG) intervention: implausible",
  "Schaltverzoegerung Hauptrelais": "Main relay: switch-off delay",
  "Segmentzeitmessung fehlerhaft": "Segment time measurement faulty",
  "Sekundaerluftpumpe nicht aktiv": "Secondary air pump not active",
  "Sekundaerluftsystem Bank 1": "Secondary air system, bank 1",
  "Sekundaerluftsystem Bank 2": "Secondary air system, bank 2",
  "Sekundaerluftventil": "Secondary air valve",
  "Sekundaerluftventil klemmt offen": "Secondary air valve stuck open",
  "Signal CAN Tankfuellstand": "CAN signal: fuel level",
  "Signal CAN Umgebungstemperatur": "CAN signal: ambient temperature",
  "Solarsensor": "Solar sensor",
  "Solarsensor oder Latentwaermespeicher Temperaturfuehler": "Solar sensor or latent-heat-accumulator temp sensor",
  "Sprungzeit Lambdasonde Bank 1": "O2 sensor response time, bank 1",
  "Sprungzeit Lambdasonde Bank 2": "O2 sensor response time, bank 2",
  "Sprungzeit NKAT-Sonde BK1": "Post-cat O2 sensor, response time, bank 1",
  "Sprungzeit NKAT-Sonde BK2": "Post-cat O2 sensor, response time, bank 2",
  "Steuergeraetefehler": "Control unit fault",
  "TAL": "TAL temperature signal",
  "TEG_DOWN_1": "Cruise control lever, down 1 (TEG)",
  "TEG_DOWN_2": "Cruise control lever, down 2 (TEG)",
  "TEG_UP_1": "Cruise control lever, up 1 (TEG)",
  "TEG_UP_2": "Cruise control lever, up 2 (TEG)",
  "TKW": "Engine coolant temperature (TKW)",
  "TKW-MAX Plausibilitaet": "Coolant temp max: plausibility",
  "TPS-Adaption": "Throttle position sensor (TPS): adaptation",
  "TPS-MAF Unplausibilitaet": "Throttle (TPS) vs. MAF: implausible",
  "TPS-Startpruefung": "Throttle position sensor (TPS): startup check",
  "Tachosignal unplausibel": "Speedometer signal: implausible",
  "Tankentlueftungsventil": "Fuel tank purge valve",
  "Tankleckdiagnose mit DMTL": "Fuel tank leak diagnosis (DMTL)",
  "Temperaturfuehler Oel": "Oil temperature sensor",
  "Thermostat klemmt offen": "Thermostat stuck open",
  "Thermostatheizung, KFK": "Thermostat heater (map-controlled cooling)",
  "Timeout CAN-Botschaft ASC1": "Timeout: CAN message ASC1",
  "Timeout CAN-Botschaft ASC3": "Timeout: CAN message ASC3",
  "Timeout CAN-Botschaft EGS1": "Timeout: CAN message EGS1 (transmission)",
  "Timeout CAN-Botschaft INSTR2": "Timeout: CAN message INSTR2 (cluster)",
  "Timeout CAN-Botschaft INSTR3": "Timeout: CAN message INSTR3 (cluster)",
  "Timeout CAN-Botschaft LWS1": "Timeout: CAN message LWS1 (steering angle)",
  "Timeout SSG - Botschaft": "Timeout: SMG (SSG) message",
  "Umgebungsdrucksensor": "Ambient pressure sensor",
  "Unplausibilitaet Gas + Bremse": "Accelerator + brake: implausible",
  "VANOS-Magnetventil Auslass-NW": "VANOS solenoid valve, exhaust camshaft",
  "VANOS-Magnetventil Einlass-NW": "VANOS solenoid valve, intake camshaft",
  "VCC-Poti 1": "VCC potentiometer 1",
  "VCC-Poti 2": "VCC potentiometer 2",
  "Variable Sauganlage": "Variable intake manifold (DISA)",
  "Verbrennungsaussetzer Zylinder 1": "Misfire, cylinder 1",
  "Verbrennungsaussetzer Zylinder 2": "Misfire, cylinder 2",
  "Verbrennungsaussetzer Zylinder 3": "Misfire, cylinder 3",
  "Verbrennungsaussetzer Zylinder 4": "Misfire, cylinder 4",
  "Verbrennungsaussetzer Zylinder 5": "Misfire, cylinder 5",
  "Verbrennungsaussetzer Zylinder 6": "Misfire, cylinder 6",
  "Verdampferfuehler": "Evaporator temperature sensor",
  "Waermetauscherfuehler": "Heat-exchanger temperature sensor",
  "Wasserventil": "Water valve",
  "ZSR Fehler (>2 Zyl.)": "Ignition-coil relay (ZSR): fault (>2 cyl.)",
  "ZSR Messwiderstand": "Ignition-coil relay (ZSR): measuring resistor",
  "Zuendung Zyl. 1": "Ignition, cylinder 1",
  "Zuendung Zyl. 2": "Ignition, cylinder 2",
  "Zuendung Zyl. 3": "Ignition, cylinder 3",
  "Zuendung Zyl. 4": "Ignition, cylinder 4",
  "Zuendung Zyl. 5": "Ignition, cylinder 5",
  "Zuendung Zyl. 6": "Ignition, cylinder 6",
  "Zuheizer Relais": "Auxiliary heater relay",
  "Zuheizer, Relais Frontscheibenheizung": "Auxiliary heater / windscreen heating relay",
  "Zusatzwasserpumpe": "Auxiliary water pump",
};
